<?php
/**
 * ApplyTransactionResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApplyTransactionResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApplyTransactionResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApplyTransactionResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'operation_succeeded' => 'bool',
        'status' => 'int',
        'error' => 'int',
        'error_text' => 'string',
        'payment_result_data' => '\OpenAPI\Client\Model\ApplyPaymentResultData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'operation_succeeded' => null,
        'status' => 'int32',
        'error' => 'int32',
        'error_text' => null,
        'payment_result_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'operation_succeeded' => false,
        'status' => false,
        'error' => false,
        'error_text' => false,
        'payment_result_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'operation_succeeded' => 'OperationSucceeded',
        'status' => 'Status',
        'error' => 'Error',
        'error_text' => 'ErrorText',
        'payment_result_data' => 'PaymentResultData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'operation_succeeded' => 'setOperationSucceeded',
        'status' => 'setStatus',
        'error' => 'setError',
        'error_text' => 'setErrorText',
        'payment_result_data' => 'setPaymentResultData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'operation_succeeded' => 'getOperationSucceeded',
        'status' => 'getStatus',
        'error' => 'getError',
        'error_text' => 'getErrorText',
        'payment_result_data' => 'getPaymentResultData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_NUMBER_1 = 1;
    public const STATUS_NUMBER_2 = 2;
    public const STATUS_NUMBER_3 = 3;
    public const ERROR_NUMBER_1 = 1;
    public const ERROR_NUMBER_2 = 2;
    public const ERROR_NUMBER_3 = 3;
    public const ERROR_NUMBER_4 = 4;
    public const ERROR_NUMBER_5 = 5;
    public const ERROR_NUMBER_6 = 6;
    public const ERROR_NUMBER_7 = 7;
    public const ERROR_NUMBER_8 = 8;
    public const ERROR_NUMBER_9 = 9;
    public const ERROR_NUMBER_10 = 10;
    public const ERROR_NUMBER_11 = 11;
    public const ERROR_NUMBER_12 = 12;
    public const ERROR_NUMBER_13 = 13;
    public const ERROR_NUMBER_14 = 14;
    public const ERROR_NUMBER_15 = 15;
    public const ERROR_NUMBER_16 = 16;
    public const ERROR_NUMBER_17 = 17;
    public const ERROR_NUMBER_18 = 18;
    public const ERROR_NUMBER_19 = 19;
    public const ERROR_NUMBER_20 = 20;
    public const ERROR_NUMBER_21 = 21;
    public const ERROR_NUMBER_22 = 22;
    public const ERROR_NUMBER_23 = 23;
    public const ERROR_NUMBER_24 = 24;
    public const ERROR_NUMBER_25 = 25;
    public const ERROR_NUMBER_26 = 26;
    public const ERROR_NUMBER_27 = 27;
    public const ERROR_NUMBER_28 = 28;
    public const ERROR_NUMBER_29 = 29;
    public const ERROR_NUMBER_30 = 30;
    public const ERROR_NUMBER_31 = 31;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_NUMBER_1,
            self::STATUS_NUMBER_2,
            self::STATUS_NUMBER_3,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getErrorAllowableValues()
    {
        return [
            self::ERROR_NUMBER_1,
            self::ERROR_NUMBER_2,
            self::ERROR_NUMBER_3,
            self::ERROR_NUMBER_4,
            self::ERROR_NUMBER_5,
            self::ERROR_NUMBER_6,
            self::ERROR_NUMBER_7,
            self::ERROR_NUMBER_8,
            self::ERROR_NUMBER_9,
            self::ERROR_NUMBER_10,
            self::ERROR_NUMBER_11,
            self::ERROR_NUMBER_12,
            self::ERROR_NUMBER_13,
            self::ERROR_NUMBER_14,
            self::ERROR_NUMBER_15,
            self::ERROR_NUMBER_16,
            self::ERROR_NUMBER_17,
            self::ERROR_NUMBER_18,
            self::ERROR_NUMBER_19,
            self::ERROR_NUMBER_20,
            self::ERROR_NUMBER_21,
            self::ERROR_NUMBER_22,
            self::ERROR_NUMBER_23,
            self::ERROR_NUMBER_24,
            self::ERROR_NUMBER_25,
            self::ERROR_NUMBER_26,
            self::ERROR_NUMBER_27,
            self::ERROR_NUMBER_28,
            self::ERROR_NUMBER_29,
            self::ERROR_NUMBER_30,
            self::ERROR_NUMBER_31,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('operation_succeeded', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('error_text', $data ?? [], null);
        $this->setIfExists('payment_result_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getErrorAllowableValues();
        if (!is_null($this->container['error']) && !in_array($this->container['error'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'error', must be one of '%s'",
                $this->container['error'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets operation_succeeded
     *
     * @return bool|null
     */
    public function getOperationSucceeded()
    {
        return $this->container['operation_succeeded'];
    }

    /**
     * Sets operation_succeeded
     *
     * @param bool|null $operation_succeeded operation_succeeded
     *
     * @return self
     */
    public function setOperationSucceeded($operation_succeeded)
    {
        if (is_null($operation_succeeded)) {
            throw new \InvalidArgumentException('non-nullable operation_succeeded cannot be null');
        }
        $this->container['operation_succeeded'] = $operation_succeeded;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets error
     *
     * @return int|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param int|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $allowedValues = $this->getErrorAllowableValues();
        if (!in_array($error, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'error', must be one of '%s'",
                    $error,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets error_text
     *
     * @return string|null
     */
    public function getErrorText()
    {
        return $this->container['error_text'];
    }

    /**
     * Sets error_text
     *
     * @param string|null $error_text error_text
     *
     * @return self
     */
    public function setErrorText($error_text)
    {
        if (is_null($error_text)) {
            throw new \InvalidArgumentException('non-nullable error_text cannot be null');
        }
        $this->container['error_text'] = $error_text;

        return $this;
    }

    /**
     * Gets payment_result_data
     *
     * @return \OpenAPI\Client\Model\ApplyPaymentResultData|null
     */
    public function getPaymentResultData()
    {
        return $this->container['payment_result_data'];
    }

    /**
     * Sets payment_result_data
     *
     * @param \OpenAPI\Client\Model\ApplyPaymentResultData|null $payment_result_data payment_result_data
     *
     * @return self
     */
    public function setPaymentResultData($payment_result_data)
    {
        if (is_null($payment_result_data)) {
            throw new \InvalidArgumentException('non-nullable payment_result_data cannot be null');
        }
        $this->container['payment_result_data'] = $payment_result_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


