<?php
/**
 * AvailableInternationalMobileProduct
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AvailableInternationalMobileProduct Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AvailableInternationalMobileProduct implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AvailableInternationalMobileProduct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'type' => 'string',
        'amount' => 'float',
        'min_amount' => 'float',
        'max_amount' => 'float',
        'tax' => 'float',
        'source_currency' => 'string',
        'destination_amount' => 'float',
        'destination_min_amount' => 'float',
        'destination_max_amount' => 'float',
        'destination_currency' => 'string',
        'validity' => 'int',
        'validity_type' => 'string',
        'tags' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'name' => null,
        'type' => null,
        'amount' => 'double',
        'min_amount' => 'double',
        'max_amount' => 'double',
        'tax' => 'double',
        'source_currency' => null,
        'destination_amount' => 'double',
        'destination_min_amount' => 'double',
        'destination_max_amount' => 'double',
        'destination_currency' => null,
        'validity' => 'int32',
        'validity_type' => null,
        'tags' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'type' => false,
        'amount' => false,
        'min_amount' => false,
        'max_amount' => false,
        'tax' => false,
        'source_currency' => false,
        'destination_amount' => false,
        'destination_min_amount' => false,
        'destination_max_amount' => false,
        'destination_currency' => false,
        'validity' => false,
        'validity_type' => false,
        'tags' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'name' => 'Name',
        'type' => 'Type',
        'amount' => 'Amount',
        'min_amount' => 'MinAmount',
        'max_amount' => 'MaxAmount',
        'tax' => 'Tax',
        'source_currency' => 'SourceCurrency',
        'destination_amount' => 'DestinationAmount',
        'destination_min_amount' => 'DestinationMinAmount',
        'destination_max_amount' => 'DestinationMaxAmount',
        'destination_currency' => 'DestinationCurrency',
        'validity' => 'Validity',
        'validity_type' => 'ValidityType',
        'tags' => 'Tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'type' => 'setType',
        'amount' => 'setAmount',
        'min_amount' => 'setMinAmount',
        'max_amount' => 'setMaxAmount',
        'tax' => 'setTax',
        'source_currency' => 'setSourceCurrency',
        'destination_amount' => 'setDestinationAmount',
        'destination_min_amount' => 'setDestinationMinAmount',
        'destination_max_amount' => 'setDestinationMaxAmount',
        'destination_currency' => 'setDestinationCurrency',
        'validity' => 'setValidity',
        'validity_type' => 'setValidityType',
        'tags' => 'setTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'type' => 'getType',
        'amount' => 'getAmount',
        'min_amount' => 'getMinAmount',
        'max_amount' => 'getMaxAmount',
        'tax' => 'getTax',
        'source_currency' => 'getSourceCurrency',
        'destination_amount' => 'getDestinationAmount',
        'destination_min_amount' => 'getDestinationMinAmount',
        'destination_max_amount' => 'getDestinationMaxAmount',
        'destination_currency' => 'getDestinationCurrency',
        'validity' => 'getValidity',
        'validity_type' => 'getValidityType',
        'tags' => 'getTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('min_amount', $data ?? [], null);
        $this->setIfExists('max_amount', $data ?? [], null);
        $this->setIfExists('tax', $data ?? [], null);
        $this->setIfExists('source_currency', $data ?? [], null);
        $this->setIfExists('destination_amount', $data ?? [], null);
        $this->setIfExists('destination_min_amount', $data ?? [], null);
        $this->setIfExists('destination_max_amount', $data ?? [], null);
        $this->setIfExists('destination_currency', $data ?? [], null);
        $this->setIfExists('validity', $data ?? [], null);
        $this->setIfExists('validity_type', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets min_amount
     *
     * @return float|null
     */
    public function getMinAmount()
    {
        return $this->container['min_amount'];
    }

    /**
     * Sets min_amount
     *
     * @param float|null $min_amount min_amount
     *
     * @return self
     */
    public function setMinAmount($min_amount)
    {
        if (is_null($min_amount)) {
            throw new \InvalidArgumentException('non-nullable min_amount cannot be null');
        }
        $this->container['min_amount'] = $min_amount;

        return $this;
    }

    /**
     * Gets max_amount
     *
     * @return float|null
     */
    public function getMaxAmount()
    {
        return $this->container['max_amount'];
    }

    /**
     * Sets max_amount
     *
     * @param float|null $max_amount max_amount
     *
     * @return self
     */
    public function setMaxAmount($max_amount)
    {
        if (is_null($max_amount)) {
            throw new \InvalidArgumentException('non-nullable max_amount cannot be null');
        }
        $this->container['max_amount'] = $max_amount;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return float|null
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param float|null $tax tax
     *
     * @return self
     */
    public function setTax($tax)
    {
        if (is_null($tax)) {
            throw new \InvalidArgumentException('non-nullable tax cannot be null');
        }
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets source_currency
     *
     * @return string|null
     */
    public function getSourceCurrency()
    {
        return $this->container['source_currency'];
    }

    /**
     * Sets source_currency
     *
     * @param string|null $source_currency source_currency
     *
     * @return self
     */
    public function setSourceCurrency($source_currency)
    {
        if (is_null($source_currency)) {
            throw new \InvalidArgumentException('non-nullable source_currency cannot be null');
        }
        $this->container['source_currency'] = $source_currency;

        return $this;
    }

    /**
     * Gets destination_amount
     *
     * @return float|null
     */
    public function getDestinationAmount()
    {
        return $this->container['destination_amount'];
    }

    /**
     * Sets destination_amount
     *
     * @param float|null $destination_amount destination_amount
     *
     * @return self
     */
    public function setDestinationAmount($destination_amount)
    {
        if (is_null($destination_amount)) {
            throw new \InvalidArgumentException('non-nullable destination_amount cannot be null');
        }
        $this->container['destination_amount'] = $destination_amount;

        return $this;
    }

    /**
     * Gets destination_min_amount
     *
     * @return float|null
     */
    public function getDestinationMinAmount()
    {
        return $this->container['destination_min_amount'];
    }

    /**
     * Sets destination_min_amount
     *
     * @param float|null $destination_min_amount destination_min_amount
     *
     * @return self
     */
    public function setDestinationMinAmount($destination_min_amount)
    {
        if (is_null($destination_min_amount)) {
            throw new \InvalidArgumentException('non-nullable destination_min_amount cannot be null');
        }
        $this->container['destination_min_amount'] = $destination_min_amount;

        return $this;
    }

    /**
     * Gets destination_max_amount
     *
     * @return float|null
     */
    public function getDestinationMaxAmount()
    {
        return $this->container['destination_max_amount'];
    }

    /**
     * Sets destination_max_amount
     *
     * @param float|null $destination_max_amount destination_max_amount
     *
     * @return self
     */
    public function setDestinationMaxAmount($destination_max_amount)
    {
        if (is_null($destination_max_amount)) {
            throw new \InvalidArgumentException('non-nullable destination_max_amount cannot be null');
        }
        $this->container['destination_max_amount'] = $destination_max_amount;

        return $this;
    }

    /**
     * Gets destination_currency
     *
     * @return string|null
     */
    public function getDestinationCurrency()
    {
        return $this->container['destination_currency'];
    }

    /**
     * Sets destination_currency
     *
     * @param string|null $destination_currency destination_currency
     *
     * @return self
     */
    public function setDestinationCurrency($destination_currency)
    {
        if (is_null($destination_currency)) {
            throw new \InvalidArgumentException('non-nullable destination_currency cannot be null');
        }
        $this->container['destination_currency'] = $destination_currency;

        return $this;
    }

    /**
     * Gets validity
     *
     * @return int|null
     */
    public function getValidity()
    {
        return $this->container['validity'];
    }

    /**
     * Sets validity
     *
     * @param int|null $validity validity
     *
     * @return self
     */
    public function setValidity($validity)
    {
        if (is_null($validity)) {
            throw new \InvalidArgumentException('non-nullable validity cannot be null');
        }
        $this->container['validity'] = $validity;

        return $this;
    }

    /**
     * Gets validity_type
     *
     * @return string|null
     */
    public function getValidityType()
    {
        return $this->container['validity_type'];
    }

    /**
     * Sets validity_type
     *
     * @param string|null $validity_type validity_type
     *
     * @return self
     */
    public function setValidityType($validity_type)
    {
        if (is_null($validity_type)) {
            throw new \InvalidArgumentException('non-nullable validity_type cannot be null');
        }
        $this->container['validity_type'] = $validity_type;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


