<?php
/**
 * AvailableProduct
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AvailableProduct Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AvailableProduct implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AvailableProduct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'country_iso' => 'string',
        'currency_code' => 'string',
        'product_currency_code' => 'string',
        'name' => 'string',
        'provider_code' => 'string',
        'product_code' => 'string',
        'product_category' => 'string',
        'product_category_logo' => 'string',
        'discount' => 'float',
        'description' => 'string',
        'product_description' => 'string',
        'product_url' => 'string',
        'reedem_desc' => 'string',
        'reedem_url' => 'string',
        'product_logo' => 'string',
        'brand_logo' => 'string',
        'terms_conditions' => 'string',
        'terms_url' => 'string',
        'privacy_url' => 'string',
        'notes' => 'string',
        'receipt_message' => 'string',
        'is_transation_cancelabled' => 'bool',
        'reference_length' => 'int',
        'is_voucher' => 'bool',
        'international_product_options_list' => '\OpenAPI\Client\Model\EzeTopGetProductsResponse[]',
        'visible_fields' => '\OpenAPI\Client\Model\VisibleFields',
        'mandatory_fields' => '\OpenAPI\Client\Model\MandatoryFields',
        'next_method_call' => 'string',
        'group_code' => 'string',
        'vfp_code' => 'string',
        'vgp_code' => 'string',
        'general_data_message' => 'string',
        'dealer_code' => 'string',
        'dealer_type' => 'string',
        'group_key' => 'string',
        'image_code' => 'string',
        'pin_expiry_time' => 'string',
        'product_options_list' => '\OpenAPI\Client\Model\AvailableProductOptions[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'country_iso' => null,
        'currency_code' => null,
        'product_currency_code' => null,
        'name' => null,
        'provider_code' => null,
        'product_code' => null,
        'product_category' => null,
        'product_category_logo' => null,
        'discount' => 'double',
        'description' => null,
        'product_description' => null,
        'product_url' => null,
        'reedem_desc' => null,
        'reedem_url' => null,
        'product_logo' => null,
        'brand_logo' => null,
        'terms_conditions' => null,
        'terms_url' => null,
        'privacy_url' => null,
        'notes' => null,
        'receipt_message' => null,
        'is_transation_cancelabled' => null,
        'reference_length' => 'int32',
        'is_voucher' => null,
        'international_product_options_list' => null,
        'visible_fields' => null,
        'mandatory_fields' => null,
        'next_method_call' => null,
        'group_code' => null,
        'vfp_code' => null,
        'vgp_code' => null,
        'general_data_message' => null,
        'dealer_code' => null,
        'dealer_type' => null,
        'group_key' => null,
        'image_code' => null,
        'pin_expiry_time' => null,
        'product_options_list' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'country_iso' => false,
        'currency_code' => false,
        'product_currency_code' => false,
        'name' => false,
        'provider_code' => false,
        'product_code' => false,
        'product_category' => false,
        'product_category_logo' => false,
        'discount' => false,
        'description' => false,
        'product_description' => false,
        'product_url' => false,
        'reedem_desc' => false,
        'reedem_url' => false,
        'product_logo' => false,
        'brand_logo' => false,
        'terms_conditions' => false,
        'terms_url' => false,
        'privacy_url' => false,
        'notes' => false,
        'receipt_message' => false,
        'is_transation_cancelabled' => false,
        'reference_length' => false,
        'is_voucher' => false,
        'international_product_options_list' => false,
        'visible_fields' => false,
        'mandatory_fields' => false,
        'next_method_call' => false,
        'group_code' => false,
        'vfp_code' => false,
        'vgp_code' => false,
        'general_data_message' => false,
        'dealer_code' => false,
        'dealer_type' => false,
        'group_key' => false,
        'image_code' => false,
        'pin_expiry_time' => false,
        'product_options_list' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_iso' => 'CountryIso',
        'currency_code' => 'CurrencyCode',
        'product_currency_code' => 'ProductCurrencyCode',
        'name' => 'Name',
        'provider_code' => 'ProviderCode',
        'product_code' => 'ProductCode',
        'product_category' => 'ProductCategory',
        'product_category_logo' => 'ProductCategoryLogo',
        'discount' => 'Discount',
        'description' => 'Description',
        'product_description' => 'ProductDescription',
        'product_url' => 'ProductUrl',
        'reedem_desc' => 'ReedemDesc',
        'reedem_url' => 'ReedemUrl',
        'product_logo' => 'ProductLogo',
        'brand_logo' => 'BrandLogo',
        'terms_conditions' => 'TermsConditions',
        'terms_url' => 'TermsUrl',
        'privacy_url' => 'PrivacyUrl',
        'notes' => 'Notes',
        'receipt_message' => 'ReceiptMessage',
        'is_transation_cancelabled' => 'IsTransationCancelabled',
        'reference_length' => 'ReferenceLength',
        'is_voucher' => 'IsVoucher',
        'international_product_options_list' => 'InternationalProductOptionsList',
        'visible_fields' => 'VisibleFields',
        'mandatory_fields' => 'MandatoryFields',
        'next_method_call' => 'NextMethodCall',
        'group_code' => 'GroupCode',
        'vfp_code' => 'VFPCode',
        'vgp_code' => 'VGPCode',
        'general_data_message' => 'GeneralDataMessage',
        'dealer_code' => 'DealerCode',
        'dealer_type' => 'DealerType',
        'group_key' => 'GroupKey',
        'image_code' => 'ImageCode',
        'pin_expiry_time' => 'PinExpiryTime',
        'product_options_list' => 'ProductOptionsList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_iso' => 'setCountryIso',
        'currency_code' => 'setCurrencyCode',
        'product_currency_code' => 'setProductCurrencyCode',
        'name' => 'setName',
        'provider_code' => 'setProviderCode',
        'product_code' => 'setProductCode',
        'product_category' => 'setProductCategory',
        'product_category_logo' => 'setProductCategoryLogo',
        'discount' => 'setDiscount',
        'description' => 'setDescription',
        'product_description' => 'setProductDescription',
        'product_url' => 'setProductUrl',
        'reedem_desc' => 'setReedemDesc',
        'reedem_url' => 'setReedemUrl',
        'product_logo' => 'setProductLogo',
        'brand_logo' => 'setBrandLogo',
        'terms_conditions' => 'setTermsConditions',
        'terms_url' => 'setTermsUrl',
        'privacy_url' => 'setPrivacyUrl',
        'notes' => 'setNotes',
        'receipt_message' => 'setReceiptMessage',
        'is_transation_cancelabled' => 'setIsTransationCancelabled',
        'reference_length' => 'setReferenceLength',
        'is_voucher' => 'setIsVoucher',
        'international_product_options_list' => 'setInternationalProductOptionsList',
        'visible_fields' => 'setVisibleFields',
        'mandatory_fields' => 'setMandatoryFields',
        'next_method_call' => 'setNextMethodCall',
        'group_code' => 'setGroupCode',
        'vfp_code' => 'setVfpCode',
        'vgp_code' => 'setVgpCode',
        'general_data_message' => 'setGeneralDataMessage',
        'dealer_code' => 'setDealerCode',
        'dealer_type' => 'setDealerType',
        'group_key' => 'setGroupKey',
        'image_code' => 'setImageCode',
        'pin_expiry_time' => 'setPinExpiryTime',
        'product_options_list' => 'setProductOptionsList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_iso' => 'getCountryIso',
        'currency_code' => 'getCurrencyCode',
        'product_currency_code' => 'getProductCurrencyCode',
        'name' => 'getName',
        'provider_code' => 'getProviderCode',
        'product_code' => 'getProductCode',
        'product_category' => 'getProductCategory',
        'product_category_logo' => 'getProductCategoryLogo',
        'discount' => 'getDiscount',
        'description' => 'getDescription',
        'product_description' => 'getProductDescription',
        'product_url' => 'getProductUrl',
        'reedem_desc' => 'getReedemDesc',
        'reedem_url' => 'getReedemUrl',
        'product_logo' => 'getProductLogo',
        'brand_logo' => 'getBrandLogo',
        'terms_conditions' => 'getTermsConditions',
        'terms_url' => 'getTermsUrl',
        'privacy_url' => 'getPrivacyUrl',
        'notes' => 'getNotes',
        'receipt_message' => 'getReceiptMessage',
        'is_transation_cancelabled' => 'getIsTransationCancelabled',
        'reference_length' => 'getReferenceLength',
        'is_voucher' => 'getIsVoucher',
        'international_product_options_list' => 'getInternationalProductOptionsList',
        'visible_fields' => 'getVisibleFields',
        'mandatory_fields' => 'getMandatoryFields',
        'next_method_call' => 'getNextMethodCall',
        'group_code' => 'getGroupCode',
        'vfp_code' => 'getVfpCode',
        'vgp_code' => 'getVgpCode',
        'general_data_message' => 'getGeneralDataMessage',
        'dealer_code' => 'getDealerCode',
        'dealer_type' => 'getDealerType',
        'group_key' => 'getGroupKey',
        'image_code' => 'getImageCode',
        'pin_expiry_time' => 'getPinExpiryTime',
        'product_options_list' => 'getProductOptionsList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('country_iso', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('product_currency_code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('provider_code', $data ?? [], null);
        $this->setIfExists('product_code', $data ?? [], null);
        $this->setIfExists('product_category', $data ?? [], null);
        $this->setIfExists('product_category_logo', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('product_description', $data ?? [], null);
        $this->setIfExists('product_url', $data ?? [], null);
        $this->setIfExists('reedem_desc', $data ?? [], null);
        $this->setIfExists('reedem_url', $data ?? [], null);
        $this->setIfExists('product_logo', $data ?? [], null);
        $this->setIfExists('brand_logo', $data ?? [], null);
        $this->setIfExists('terms_conditions', $data ?? [], null);
        $this->setIfExists('terms_url', $data ?? [], null);
        $this->setIfExists('privacy_url', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('receipt_message', $data ?? [], null);
        $this->setIfExists('is_transation_cancelabled', $data ?? [], null);
        $this->setIfExists('reference_length', $data ?? [], null);
        $this->setIfExists('is_voucher', $data ?? [], null);
        $this->setIfExists('international_product_options_list', $data ?? [], null);
        $this->setIfExists('visible_fields', $data ?? [], null);
        $this->setIfExists('mandatory_fields', $data ?? [], null);
        $this->setIfExists('next_method_call', $data ?? [], null);
        $this->setIfExists('group_code', $data ?? [], null);
        $this->setIfExists('vfp_code', $data ?? [], null);
        $this->setIfExists('vgp_code', $data ?? [], null);
        $this->setIfExists('general_data_message', $data ?? [], null);
        $this->setIfExists('dealer_code', $data ?? [], null);
        $this->setIfExists('dealer_type', $data ?? [], null);
        $this->setIfExists('group_key', $data ?? [], null);
        $this->setIfExists('image_code', $data ?? [], null);
        $this->setIfExists('pin_expiry_time', $data ?? [], null);
        $this->setIfExists('product_options_list', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_iso
     *
     * @return string|null
     */
    public function getCountryIso()
    {
        return $this->container['country_iso'];
    }

    /**
     * Sets country_iso
     *
     * @param string|null $country_iso country_iso
     *
     * @return self
     */
    public function setCountryIso($country_iso)
    {
        if (is_null($country_iso)) {
            throw new \InvalidArgumentException('non-nullable country_iso cannot be null');
        }
        $this->container['country_iso'] = $country_iso;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code currency_code
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets product_currency_code
     *
     * @return string|null
     */
    public function getProductCurrencyCode()
    {
        return $this->container['product_currency_code'];
    }

    /**
     * Sets product_currency_code
     *
     * @param string|null $product_currency_code product_currency_code
     *
     * @return self
     */
    public function setProductCurrencyCode($product_currency_code)
    {
        if (is_null($product_currency_code)) {
            throw new \InvalidArgumentException('non-nullable product_currency_code cannot be null');
        }
        $this->container['product_currency_code'] = $product_currency_code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets provider_code
     *
     * @return string|null
     */
    public function getProviderCode()
    {
        return $this->container['provider_code'];
    }

    /**
     * Sets provider_code
     *
     * @param string|null $provider_code provider_code
     *
     * @return self
     */
    public function setProviderCode($provider_code)
    {
        if (is_null($provider_code)) {
            throw new \InvalidArgumentException('non-nullable provider_code cannot be null');
        }
        $this->container['provider_code'] = $provider_code;

        return $this;
    }

    /**
     * Gets product_code
     *
     * @return string|null
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     *
     * @param string|null $product_code product_code
     *
     * @return self
     */
    public function setProductCode($product_code)
    {
        if (is_null($product_code)) {
            throw new \InvalidArgumentException('non-nullable product_code cannot be null');
        }
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets product_category
     *
     * @return string|null
     */
    public function getProductCategory()
    {
        return $this->container['product_category'];
    }

    /**
     * Sets product_category
     *
     * @param string|null $product_category product_category
     *
     * @return self
     */
    public function setProductCategory($product_category)
    {
        if (is_null($product_category)) {
            throw new \InvalidArgumentException('non-nullable product_category cannot be null');
        }
        $this->container['product_category'] = $product_category;

        return $this;
    }

    /**
     * Gets product_category_logo
     *
     * @return string|null
     */
    public function getProductCategoryLogo()
    {
        return $this->container['product_category_logo'];
    }

    /**
     * Sets product_category_logo
     *
     * @param string|null $product_category_logo product_category_logo
     *
     * @return self
     */
    public function setProductCategoryLogo($product_category_logo)
    {
        if (is_null($product_category_logo)) {
            throw new \InvalidArgumentException('non-nullable product_category_logo cannot be null');
        }
        $this->container['product_category_logo'] = $product_category_logo;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return float|null
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param float|null $discount discount
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets product_description
     *
     * @return string|null
     */
    public function getProductDescription()
    {
        return $this->container['product_description'];
    }

    /**
     * Sets product_description
     *
     * @param string|null $product_description product_description
     *
     * @return self
     */
    public function setProductDescription($product_description)
    {
        if (is_null($product_description)) {
            throw new \InvalidArgumentException('non-nullable product_description cannot be null');
        }
        $this->container['product_description'] = $product_description;

        return $this;
    }

    /**
     * Gets product_url
     *
     * @return string|null
     */
    public function getProductUrl()
    {
        return $this->container['product_url'];
    }

    /**
     * Sets product_url
     *
     * @param string|null $product_url product_url
     *
     * @return self
     */
    public function setProductUrl($product_url)
    {
        if (is_null($product_url)) {
            throw new \InvalidArgumentException('non-nullable product_url cannot be null');
        }
        $this->container['product_url'] = $product_url;

        return $this;
    }

    /**
     * Gets reedem_desc
     *
     * @return string|null
     */
    public function getReedemDesc()
    {
        return $this->container['reedem_desc'];
    }

    /**
     * Sets reedem_desc
     *
     * @param string|null $reedem_desc reedem_desc
     *
     * @return self
     */
    public function setReedemDesc($reedem_desc)
    {
        if (is_null($reedem_desc)) {
            throw new \InvalidArgumentException('non-nullable reedem_desc cannot be null');
        }
        $this->container['reedem_desc'] = $reedem_desc;

        return $this;
    }

    /**
     * Gets reedem_url
     *
     * @return string|null
     */
    public function getReedemUrl()
    {
        return $this->container['reedem_url'];
    }

    /**
     * Sets reedem_url
     *
     * @param string|null $reedem_url reedem_url
     *
     * @return self
     */
    public function setReedemUrl($reedem_url)
    {
        if (is_null($reedem_url)) {
            throw new \InvalidArgumentException('non-nullable reedem_url cannot be null');
        }
        $this->container['reedem_url'] = $reedem_url;

        return $this;
    }

    /**
     * Gets product_logo
     *
     * @return string|null
     */
    public function getProductLogo()
    {
        return $this->container['product_logo'];
    }

    /**
     * Sets product_logo
     *
     * @param string|null $product_logo product_logo
     *
     * @return self
     */
    public function setProductLogo($product_logo)
    {
        if (is_null($product_logo)) {
            throw new \InvalidArgumentException('non-nullable product_logo cannot be null');
        }
        $this->container['product_logo'] = $product_logo;

        return $this;
    }

    /**
     * Gets brand_logo
     *
     * @return string|null
     */
    public function getBrandLogo()
    {
        return $this->container['brand_logo'];
    }

    /**
     * Sets brand_logo
     *
     * @param string|null $brand_logo brand_logo
     *
     * @return self
     */
    public function setBrandLogo($brand_logo)
    {
        if (is_null($brand_logo)) {
            throw new \InvalidArgumentException('non-nullable brand_logo cannot be null');
        }
        $this->container['brand_logo'] = $brand_logo;

        return $this;
    }

    /**
     * Gets terms_conditions
     *
     * @return string|null
     */
    public function getTermsConditions()
    {
        return $this->container['terms_conditions'];
    }

    /**
     * Sets terms_conditions
     *
     * @param string|null $terms_conditions terms_conditions
     *
     * @return self
     */
    public function setTermsConditions($terms_conditions)
    {
        if (is_null($terms_conditions)) {
            throw new \InvalidArgumentException('non-nullable terms_conditions cannot be null');
        }
        $this->container['terms_conditions'] = $terms_conditions;

        return $this;
    }

    /**
     * Gets terms_url
     *
     * @return string|null
     */
    public function getTermsUrl()
    {
        return $this->container['terms_url'];
    }

    /**
     * Sets terms_url
     *
     * @param string|null $terms_url terms_url
     *
     * @return self
     */
    public function setTermsUrl($terms_url)
    {
        if (is_null($terms_url)) {
            throw new \InvalidArgumentException('non-nullable terms_url cannot be null');
        }
        $this->container['terms_url'] = $terms_url;

        return $this;
    }

    /**
     * Gets privacy_url
     *
     * @return string|null
     */
    public function getPrivacyUrl()
    {
        return $this->container['privacy_url'];
    }

    /**
     * Sets privacy_url
     *
     * @param string|null $privacy_url privacy_url
     *
     * @return self
     */
    public function setPrivacyUrl($privacy_url)
    {
        if (is_null($privacy_url)) {
            throw new \InvalidArgumentException('non-nullable privacy_url cannot be null');
        }
        $this->container['privacy_url'] = $privacy_url;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes notes
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            throw new \InvalidArgumentException('non-nullable notes cannot be null');
        }
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets receipt_message
     *
     * @return string|null
     */
    public function getReceiptMessage()
    {
        return $this->container['receipt_message'];
    }

    /**
     * Sets receipt_message
     *
     * @param string|null $receipt_message receipt_message
     *
     * @return self
     */
    public function setReceiptMessage($receipt_message)
    {
        if (is_null($receipt_message)) {
            throw new \InvalidArgumentException('non-nullable receipt_message cannot be null');
        }
        $this->container['receipt_message'] = $receipt_message;

        return $this;
    }

    /**
     * Gets is_transation_cancelabled
     *
     * @return bool|null
     */
    public function getIsTransationCancelabled()
    {
        return $this->container['is_transation_cancelabled'];
    }

    /**
     * Sets is_transation_cancelabled
     *
     * @param bool|null $is_transation_cancelabled is_transation_cancelabled
     *
     * @return self
     */
    public function setIsTransationCancelabled($is_transation_cancelabled)
    {
        if (is_null($is_transation_cancelabled)) {
            throw new \InvalidArgumentException('non-nullable is_transation_cancelabled cannot be null');
        }
        $this->container['is_transation_cancelabled'] = $is_transation_cancelabled;

        return $this;
    }

    /**
     * Gets reference_length
     *
     * @return int|null
     */
    public function getReferenceLength()
    {
        return $this->container['reference_length'];
    }

    /**
     * Sets reference_length
     *
     * @param int|null $reference_length reference_length
     *
     * @return self
     */
    public function setReferenceLength($reference_length)
    {
        if (is_null($reference_length)) {
            throw new \InvalidArgumentException('non-nullable reference_length cannot be null');
        }
        $this->container['reference_length'] = $reference_length;

        return $this;
    }

    /**
     * Gets is_voucher
     *
     * @return bool|null
     */
    public function getIsVoucher()
    {
        return $this->container['is_voucher'];
    }

    /**
     * Sets is_voucher
     *
     * @param bool|null $is_voucher is_voucher
     *
     * @return self
     */
    public function setIsVoucher($is_voucher)
    {
        if (is_null($is_voucher)) {
            throw new \InvalidArgumentException('non-nullable is_voucher cannot be null');
        }
        $this->container['is_voucher'] = $is_voucher;

        return $this;
    }

    /**
     * Gets international_product_options_list
     *
     * @return \OpenAPI\Client\Model\EzeTopGetProductsResponse[]|null
     */
    public function getInternationalProductOptionsList()
    {
        return $this->container['international_product_options_list'];
    }

    /**
     * Sets international_product_options_list
     *
     * @param \OpenAPI\Client\Model\EzeTopGetProductsResponse[]|null $international_product_options_list international_product_options_list
     *
     * @return self
     */
    public function setInternationalProductOptionsList($international_product_options_list)
    {
        if (is_null($international_product_options_list)) {
            throw new \InvalidArgumentException('non-nullable international_product_options_list cannot be null');
        }
        $this->container['international_product_options_list'] = $international_product_options_list;

        return $this;
    }

    /**
     * Gets visible_fields
     *
     * @return \OpenAPI\Client\Model\VisibleFields|null
     */
    public function getVisibleFields()
    {
        return $this->container['visible_fields'];
    }

    /**
     * Sets visible_fields
     *
     * @param \OpenAPI\Client\Model\VisibleFields|null $visible_fields visible_fields
     *
     * @return self
     */
    public function setVisibleFields($visible_fields)
    {
        if (is_null($visible_fields)) {
            throw new \InvalidArgumentException('non-nullable visible_fields cannot be null');
        }
        $this->container['visible_fields'] = $visible_fields;

        return $this;
    }

    /**
     * Gets mandatory_fields
     *
     * @return \OpenAPI\Client\Model\MandatoryFields|null
     */
    public function getMandatoryFields()
    {
        return $this->container['mandatory_fields'];
    }

    /**
     * Sets mandatory_fields
     *
     * @param \OpenAPI\Client\Model\MandatoryFields|null $mandatory_fields mandatory_fields
     *
     * @return self
     */
    public function setMandatoryFields($mandatory_fields)
    {
        if (is_null($mandatory_fields)) {
            throw new \InvalidArgumentException('non-nullable mandatory_fields cannot be null');
        }
        $this->container['mandatory_fields'] = $mandatory_fields;

        return $this;
    }

    /**
     * Gets next_method_call
     *
     * @return string|null
     */
    public function getNextMethodCall()
    {
        return $this->container['next_method_call'];
    }

    /**
     * Sets next_method_call
     *
     * @param string|null $next_method_call next_method_call
     *
     * @return self
     */
    public function setNextMethodCall($next_method_call)
    {
        if (is_null($next_method_call)) {
            throw new \InvalidArgumentException('non-nullable next_method_call cannot be null');
        }
        $this->container['next_method_call'] = $next_method_call;

        return $this;
    }

    /**
     * Gets group_code
     *
     * @return string|null
     */
    public function getGroupCode()
    {
        return $this->container['group_code'];
    }

    /**
     * Sets group_code
     *
     * @param string|null $group_code group_code
     *
     * @return self
     */
    public function setGroupCode($group_code)
    {
        if (is_null($group_code)) {
            throw new \InvalidArgumentException('non-nullable group_code cannot be null');
        }
        $this->container['group_code'] = $group_code;

        return $this;
    }

    /**
     * Gets vfp_code
     *
     * @return string|null
     */
    public function getVfpCode()
    {
        return $this->container['vfp_code'];
    }

    /**
     * Sets vfp_code
     *
     * @param string|null $vfp_code vfp_code
     *
     * @return self
     */
    public function setVfpCode($vfp_code)
    {
        if (is_null($vfp_code)) {
            throw new \InvalidArgumentException('non-nullable vfp_code cannot be null');
        }
        $this->container['vfp_code'] = $vfp_code;

        return $this;
    }

    /**
     * Gets vgp_code
     *
     * @return string|null
     */
    public function getVgpCode()
    {
        return $this->container['vgp_code'];
    }

    /**
     * Sets vgp_code
     *
     * @param string|null $vgp_code vgp_code
     *
     * @return self
     */
    public function setVgpCode($vgp_code)
    {
        if (is_null($vgp_code)) {
            throw new \InvalidArgumentException('non-nullable vgp_code cannot be null');
        }
        $this->container['vgp_code'] = $vgp_code;

        return $this;
    }

    /**
     * Gets general_data_message
     *
     * @return string|null
     */
    public function getGeneralDataMessage()
    {
        return $this->container['general_data_message'];
    }

    /**
     * Sets general_data_message
     *
     * @param string|null $general_data_message general_data_message
     *
     * @return self
     */
    public function setGeneralDataMessage($general_data_message)
    {
        if (is_null($general_data_message)) {
            throw new \InvalidArgumentException('non-nullable general_data_message cannot be null');
        }
        $this->container['general_data_message'] = $general_data_message;

        return $this;
    }

    /**
     * Gets dealer_code
     *
     * @return string|null
     */
    public function getDealerCode()
    {
        return $this->container['dealer_code'];
    }

    /**
     * Sets dealer_code
     *
     * @param string|null $dealer_code dealer_code
     *
     * @return self
     */
    public function setDealerCode($dealer_code)
    {
        if (is_null($dealer_code)) {
            throw new \InvalidArgumentException('non-nullable dealer_code cannot be null');
        }
        $this->container['dealer_code'] = $dealer_code;

        return $this;
    }

    /**
     * Gets dealer_type
     *
     * @return string|null
     */
    public function getDealerType()
    {
        return $this->container['dealer_type'];
    }

    /**
     * Sets dealer_type
     *
     * @param string|null $dealer_type dealer_type
     *
     * @return self
     */
    public function setDealerType($dealer_type)
    {
        if (is_null($dealer_type)) {
            throw new \InvalidArgumentException('non-nullable dealer_type cannot be null');
        }
        $this->container['dealer_type'] = $dealer_type;

        return $this;
    }

    /**
     * Gets group_key
     *
     * @return string|null
     */
    public function getGroupKey()
    {
        return $this->container['group_key'];
    }

    /**
     * Sets group_key
     *
     * @param string|null $group_key group_key
     *
     * @return self
     */
    public function setGroupKey($group_key)
    {
        if (is_null($group_key)) {
            throw new \InvalidArgumentException('non-nullable group_key cannot be null');
        }
        $this->container['group_key'] = $group_key;

        return $this;
    }

    /**
     * Gets image_code
     *
     * @return string|null
     */
    public function getImageCode()
    {
        return $this->container['image_code'];
    }

    /**
     * Sets image_code
     *
     * @param string|null $image_code image_code
     *
     * @return self
     */
    public function setImageCode($image_code)
    {
        if (is_null($image_code)) {
            throw new \InvalidArgumentException('non-nullable image_code cannot be null');
        }
        $this->container['image_code'] = $image_code;

        return $this;
    }

    /**
     * Gets pin_expiry_time
     *
     * @return string|null
     */
    public function getPinExpiryTime()
    {
        return $this->container['pin_expiry_time'];
    }

    /**
     * Sets pin_expiry_time
     *
     * @param string|null $pin_expiry_time pin_expiry_time
     *
     * @return self
     */
    public function setPinExpiryTime($pin_expiry_time)
    {
        if (is_null($pin_expiry_time)) {
            throw new \InvalidArgumentException('non-nullable pin_expiry_time cannot be null');
        }
        $this->container['pin_expiry_time'] = $pin_expiry_time;

        return $this;
    }

    /**
     * Gets product_options_list
     *
     * @return \OpenAPI\Client\Model\AvailableProductOptions[]|null
     */
    public function getProductOptionsList()
    {
        return $this->container['product_options_list'];
    }

    /**
     * Sets product_options_list
     *
     * @param \OpenAPI\Client\Model\AvailableProductOptions[]|null $product_options_list product_options_list
     *
     * @return self
     */
    public function setProductOptionsList($product_options_list)
    {
        if (is_null($product_options_list)) {
            throw new \InvalidArgumentException('non-nullable product_options_list cannot be null');
        }
        $this->container['product_options_list'] = $product_options_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


