<?php
/**
 * AvailableProductOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AvailableProductOptions Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AvailableProductOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AvailableProductOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'product_option_code' => 'string',
        'ean_sku_upc' => 'string',
        'description' => 'string',
        'logo' => 'string',
        'value' => 'float',
        'min_max_face_range_value' => '\OpenAPI\Client\Model\MinMaxFaceRangeValue',
        'min_max_range_value' => '\OpenAPI\Client\Model\MinMaxRangeValue',
        'recharge_bonus' => 'string',
        'recharge_bonus_percent' => 'string',
        'recharge_cost' => 'string',
        'vality_period' => 'string',
        'recharge_value_category_description' => 'string',
        'vality_period_bonus' => 'string',
        'message' => 'string',
        'recharge_value_key' => 'string',
        'recharge_bonus_category_description' => 'string',
        'branch_code' => 'string',
        'recharge_value_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'product_option_code' => null,
        'ean_sku_upc' => null,
        'description' => null,
        'logo' => null,
        'value' => 'double',
        'min_max_face_range_value' => null,
        'min_max_range_value' => null,
        'recharge_bonus' => null,
        'recharge_bonus_percent' => null,
        'recharge_cost' => null,
        'vality_period' => null,
        'recharge_value_category_description' => null,
        'vality_period_bonus' => null,
        'message' => null,
        'recharge_value_key' => null,
        'recharge_bonus_category_description' => null,
        'branch_code' => null,
        'recharge_value_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'product_option_code' => false,
        'ean_sku_upc' => false,
        'description' => false,
        'logo' => false,
        'value' => false,
        'min_max_face_range_value' => false,
        'min_max_range_value' => false,
        'recharge_bonus' => false,
        'recharge_bonus_percent' => false,
        'recharge_cost' => false,
        'vality_period' => false,
        'recharge_value_category_description' => false,
        'vality_period_bonus' => false,
        'message' => false,
        'recharge_value_key' => false,
        'recharge_bonus_category_description' => false,
        'branch_code' => false,
        'recharge_value_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'product_option_code' => 'ProductOptionCode',
        'ean_sku_upc' => 'EanSkuUpc',
        'description' => 'Description',
        'logo' => 'Logo',
        'value' => 'Value',
        'min_max_face_range_value' => 'MinMaxFaceRangeValue',
        'min_max_range_value' => 'MinMaxRangeValue',
        'recharge_bonus' => 'RechargeBonus',
        'recharge_bonus_percent' => 'RechargeBonusPercent',
        'recharge_cost' => 'RechargeCost',
        'vality_period' => 'ValityPeriod',
        'recharge_value_category_description' => 'RechargeValueCategoryDescription',
        'vality_period_bonus' => 'ValityPeriodBonus',
        'message' => 'Message',
        'recharge_value_key' => 'RechargeValueKey',
        'recharge_bonus_category_description' => 'RechargeBonusCategoryDescription',
        'branch_code' => 'BranchCode',
        'recharge_value_code' => 'RechargeValueCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'product_option_code' => 'setProductOptionCode',
        'ean_sku_upc' => 'setEanSkuUpc',
        'description' => 'setDescription',
        'logo' => 'setLogo',
        'value' => 'setValue',
        'min_max_face_range_value' => 'setMinMaxFaceRangeValue',
        'min_max_range_value' => 'setMinMaxRangeValue',
        'recharge_bonus' => 'setRechargeBonus',
        'recharge_bonus_percent' => 'setRechargeBonusPercent',
        'recharge_cost' => 'setRechargeCost',
        'vality_period' => 'setValityPeriod',
        'recharge_value_category_description' => 'setRechargeValueCategoryDescription',
        'vality_period_bonus' => 'setValityPeriodBonus',
        'message' => 'setMessage',
        'recharge_value_key' => 'setRechargeValueKey',
        'recharge_bonus_category_description' => 'setRechargeBonusCategoryDescription',
        'branch_code' => 'setBranchCode',
        'recharge_value_code' => 'setRechargeValueCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'product_option_code' => 'getProductOptionCode',
        'ean_sku_upc' => 'getEanSkuUpc',
        'description' => 'getDescription',
        'logo' => 'getLogo',
        'value' => 'getValue',
        'min_max_face_range_value' => 'getMinMaxFaceRangeValue',
        'min_max_range_value' => 'getMinMaxRangeValue',
        'recharge_bonus' => 'getRechargeBonus',
        'recharge_bonus_percent' => 'getRechargeBonusPercent',
        'recharge_cost' => 'getRechargeCost',
        'vality_period' => 'getValityPeriod',
        'recharge_value_category_description' => 'getRechargeValueCategoryDescription',
        'vality_period_bonus' => 'getValityPeriodBonus',
        'message' => 'getMessage',
        'recharge_value_key' => 'getRechargeValueKey',
        'recharge_bonus_category_description' => 'getRechargeBonusCategoryDescription',
        'branch_code' => 'getBranchCode',
        'recharge_value_code' => 'getRechargeValueCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('product_option_code', $data ?? [], null);
        $this->setIfExists('ean_sku_upc', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('logo', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('min_max_face_range_value', $data ?? [], null);
        $this->setIfExists('min_max_range_value', $data ?? [], null);
        $this->setIfExists('recharge_bonus', $data ?? [], null);
        $this->setIfExists('recharge_bonus_percent', $data ?? [], null);
        $this->setIfExists('recharge_cost', $data ?? [], null);
        $this->setIfExists('vality_period', $data ?? [], null);
        $this->setIfExists('recharge_value_category_description', $data ?? [], null);
        $this->setIfExists('vality_period_bonus', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('recharge_value_key', $data ?? [], null);
        $this->setIfExists('recharge_bonus_category_description', $data ?? [], null);
        $this->setIfExists('branch_code', $data ?? [], null);
        $this->setIfExists('recharge_value_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets product_option_code
     *
     * @return string|null
     */
    public function getProductOptionCode()
    {
        return $this->container['product_option_code'];
    }

    /**
     * Sets product_option_code
     *
     * @param string|null $product_option_code product_option_code
     *
     * @return self
     */
    public function setProductOptionCode($product_option_code)
    {
        if (is_null($product_option_code)) {
            throw new \InvalidArgumentException('non-nullable product_option_code cannot be null');
        }
        $this->container['product_option_code'] = $product_option_code;

        return $this;
    }

    /**
     * Gets ean_sku_upc
     *
     * @return string|null
     */
    public function getEanSkuUpc()
    {
        return $this->container['ean_sku_upc'];
    }

    /**
     * Sets ean_sku_upc
     *
     * @param string|null $ean_sku_upc ean_sku_upc
     *
     * @return self
     */
    public function setEanSkuUpc($ean_sku_upc)
    {
        if (is_null($ean_sku_upc)) {
            throw new \InvalidArgumentException('non-nullable ean_sku_upc cannot be null');
        }
        $this->container['ean_sku_upc'] = $ean_sku_upc;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return string|null
     */
    public function getLogo()
    {
        return $this->container['logo'];
    }

    /**
     * Sets logo
     *
     * @param string|null $logo logo
     *
     * @return self
     */
    public function setLogo($logo)
    {
        if (is_null($logo)) {
            throw new \InvalidArgumentException('non-nullable logo cannot be null');
        }
        $this->container['logo'] = $logo;

        return $this;
    }

    /**
     * Gets value
     *
     * @return float|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param float|null $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets min_max_face_range_value
     *
     * @return \OpenAPI\Client\Model\MinMaxFaceRangeValue|null
     */
    public function getMinMaxFaceRangeValue()
    {
        return $this->container['min_max_face_range_value'];
    }

    /**
     * Sets min_max_face_range_value
     *
     * @param \OpenAPI\Client\Model\MinMaxFaceRangeValue|null $min_max_face_range_value min_max_face_range_value
     *
     * @return self
     */
    public function setMinMaxFaceRangeValue($min_max_face_range_value)
    {
        if (is_null($min_max_face_range_value)) {
            throw new \InvalidArgumentException('non-nullable min_max_face_range_value cannot be null');
        }
        $this->container['min_max_face_range_value'] = $min_max_face_range_value;

        return $this;
    }

    /**
     * Gets min_max_range_value
     *
     * @return \OpenAPI\Client\Model\MinMaxRangeValue|null
     */
    public function getMinMaxRangeValue()
    {
        return $this->container['min_max_range_value'];
    }

    /**
     * Sets min_max_range_value
     *
     * @param \OpenAPI\Client\Model\MinMaxRangeValue|null $min_max_range_value min_max_range_value
     *
     * @return self
     */
    public function setMinMaxRangeValue($min_max_range_value)
    {
        if (is_null($min_max_range_value)) {
            throw new \InvalidArgumentException('non-nullable min_max_range_value cannot be null');
        }
        $this->container['min_max_range_value'] = $min_max_range_value;

        return $this;
    }

    /**
     * Gets recharge_bonus
     *
     * @return string|null
     */
    public function getRechargeBonus()
    {
        return $this->container['recharge_bonus'];
    }

    /**
     * Sets recharge_bonus
     *
     * @param string|null $recharge_bonus recharge_bonus
     *
     * @return self
     */
    public function setRechargeBonus($recharge_bonus)
    {
        if (is_null($recharge_bonus)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus cannot be null');
        }
        $this->container['recharge_bonus'] = $recharge_bonus;

        return $this;
    }

    /**
     * Gets recharge_bonus_percent
     *
     * @return string|null
     */
    public function getRechargeBonusPercent()
    {
        return $this->container['recharge_bonus_percent'];
    }

    /**
     * Sets recharge_bonus_percent
     *
     * @param string|null $recharge_bonus_percent recharge_bonus_percent
     *
     * @return self
     */
    public function setRechargeBonusPercent($recharge_bonus_percent)
    {
        if (is_null($recharge_bonus_percent)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus_percent cannot be null');
        }
        $this->container['recharge_bonus_percent'] = $recharge_bonus_percent;

        return $this;
    }

    /**
     * Gets recharge_cost
     *
     * @return string|null
     */
    public function getRechargeCost()
    {
        return $this->container['recharge_cost'];
    }

    /**
     * Sets recharge_cost
     *
     * @param string|null $recharge_cost recharge_cost
     *
     * @return self
     */
    public function setRechargeCost($recharge_cost)
    {
        if (is_null($recharge_cost)) {
            throw new \InvalidArgumentException('non-nullable recharge_cost cannot be null');
        }
        $this->container['recharge_cost'] = $recharge_cost;

        return $this;
    }

    /**
     * Gets vality_period
     *
     * @return string|null
     */
    public function getValityPeriod()
    {
        return $this->container['vality_period'];
    }

    /**
     * Sets vality_period
     *
     * @param string|null $vality_period vality_period
     *
     * @return self
     */
    public function setValityPeriod($vality_period)
    {
        if (is_null($vality_period)) {
            throw new \InvalidArgumentException('non-nullable vality_period cannot be null');
        }
        $this->container['vality_period'] = $vality_period;

        return $this;
    }

    /**
     * Gets recharge_value_category_description
     *
     * @return string|null
     */
    public function getRechargeValueCategoryDescription()
    {
        return $this->container['recharge_value_category_description'];
    }

    /**
     * Sets recharge_value_category_description
     *
     * @param string|null $recharge_value_category_description recharge_value_category_description
     *
     * @return self
     */
    public function setRechargeValueCategoryDescription($recharge_value_category_description)
    {
        if (is_null($recharge_value_category_description)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_category_description cannot be null');
        }
        $this->container['recharge_value_category_description'] = $recharge_value_category_description;

        return $this;
    }

    /**
     * Gets vality_period_bonus
     *
     * @return string|null
     */
    public function getValityPeriodBonus()
    {
        return $this->container['vality_period_bonus'];
    }

    /**
     * Sets vality_period_bonus
     *
     * @param string|null $vality_period_bonus vality_period_bonus
     *
     * @return self
     */
    public function setValityPeriodBonus($vality_period_bonus)
    {
        if (is_null($vality_period_bonus)) {
            throw new \InvalidArgumentException('non-nullable vality_period_bonus cannot be null');
        }
        $this->container['vality_period_bonus'] = $vality_period_bonus;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets recharge_value_key
     *
     * @return string|null
     */
    public function getRechargeValueKey()
    {
        return $this->container['recharge_value_key'];
    }

    /**
     * Sets recharge_value_key
     *
     * @param string|null $recharge_value_key recharge_value_key
     *
     * @return self
     */
    public function setRechargeValueKey($recharge_value_key)
    {
        if (is_null($recharge_value_key)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_key cannot be null');
        }
        $this->container['recharge_value_key'] = $recharge_value_key;

        return $this;
    }

    /**
     * Gets recharge_bonus_category_description
     *
     * @return string|null
     */
    public function getRechargeBonusCategoryDescription()
    {
        return $this->container['recharge_bonus_category_description'];
    }

    /**
     * Sets recharge_bonus_category_description
     *
     * @param string|null $recharge_bonus_category_description recharge_bonus_category_description
     *
     * @return self
     */
    public function setRechargeBonusCategoryDescription($recharge_bonus_category_description)
    {
        if (is_null($recharge_bonus_category_description)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus_category_description cannot be null');
        }
        $this->container['recharge_bonus_category_description'] = $recharge_bonus_category_description;

        return $this;
    }

    /**
     * Gets branch_code
     *
     * @return string|null
     */
    public function getBranchCode()
    {
        return $this->container['branch_code'];
    }

    /**
     * Sets branch_code
     *
     * @param string|null $branch_code branch_code
     *
     * @return self
     */
    public function setBranchCode($branch_code)
    {
        if (is_null($branch_code)) {
            throw new \InvalidArgumentException('non-nullable branch_code cannot be null');
        }
        $this->container['branch_code'] = $branch_code;

        return $this;
    }

    /**
     * Gets recharge_value_code
     *
     * @return string|null
     */
    public function getRechargeValueCode()
    {
        return $this->container['recharge_value_code'];
    }

    /**
     * Sets recharge_value_code
     *
     * @param string|null $recharge_value_code recharge_value_code
     *
     * @return self
     */
    public function setRechargeValueCode($recharge_value_code)
    {
        if (is_null($recharge_value_code)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_code cannot be null');
        }
        $this->container['recharge_value_code'] = $recharge_value_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


