<?php
/**
 * AvailableCountriesResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AvailableCountriesResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AvailableCountriesResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AvailableCountriesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'operation_succeeded' => 'bool',
        'error' => 'int',
        'error_text' => 'string',
        'product_type_code' => 'string',
        'product_code' => 'string',
        'provider_code' => 'string',
        'items' => '\OpenAPI\Client\Model\AvailableCountries',
        'visible_fields' => '\OpenAPI\Client\Model\VisibleFields',
        'mandatory_fields' => '\OpenAPI\Client\Model\MandatoryFields',
        'next_method_call' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'operation_succeeded' => null,
        'error' => 'int32',
        'error_text' => null,
        'product_type_code' => null,
        'product_code' => null,
        'provider_code' => null,
        'items' => null,
        'visible_fields' => null,
        'mandatory_fields' => null,
        'next_method_call' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'operation_succeeded' => false,
        'error' => false,
        'error_text' => false,
        'product_type_code' => false,
        'product_code' => false,
        'provider_code' => false,
        'items' => false,
        'visible_fields' => false,
        'mandatory_fields' => false,
        'next_method_call' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'operation_succeeded' => 'OperationSucceeded',
        'error' => 'Error',
        'error_text' => 'ErrorText',
        'product_type_code' => 'ProductTypeCode',
        'product_code' => 'ProductCode',
        'provider_code' => 'ProviderCode',
        'items' => 'Items',
        'visible_fields' => 'VisibleFields',
        'mandatory_fields' => 'MandatoryFields',
        'next_method_call' => 'NextMethodCall'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'operation_succeeded' => 'setOperationSucceeded',
        'error' => 'setError',
        'error_text' => 'setErrorText',
        'product_type_code' => 'setProductTypeCode',
        'product_code' => 'setProductCode',
        'provider_code' => 'setProviderCode',
        'items' => 'setItems',
        'visible_fields' => 'setVisibleFields',
        'mandatory_fields' => 'setMandatoryFields',
        'next_method_call' => 'setNextMethodCall'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'operation_succeeded' => 'getOperationSucceeded',
        'error' => 'getError',
        'error_text' => 'getErrorText',
        'product_type_code' => 'getProductTypeCode',
        'product_code' => 'getProductCode',
        'provider_code' => 'getProviderCode',
        'items' => 'getItems',
        'visible_fields' => 'getVisibleFields',
        'mandatory_fields' => 'getMandatoryFields',
        'next_method_call' => 'getNextMethodCall'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ERROR_NUMBER_0 = 0;
    public const ERROR_NUMBER_1 = 1;
    public const ERROR_NUMBER_2 = 2;
    public const ERROR_NUMBER_3 = 3;
    public const ERROR_NUMBER_4 = 4;
    public const ERROR_NUMBER_5 = 5;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getErrorAllowableValues()
    {
        return [
            self::ERROR_NUMBER_0,
            self::ERROR_NUMBER_1,
            self::ERROR_NUMBER_2,
            self::ERROR_NUMBER_3,
            self::ERROR_NUMBER_4,
            self::ERROR_NUMBER_5,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('operation_succeeded', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('error_text', $data ?? [], null);
        $this->setIfExists('product_type_code', $data ?? [], null);
        $this->setIfExists('product_code', $data ?? [], null);
        $this->setIfExists('provider_code', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
        $this->setIfExists('visible_fields', $data ?? [], null);
        $this->setIfExists('mandatory_fields', $data ?? [], null);
        $this->setIfExists('next_method_call', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getErrorAllowableValues();
        if (!is_null($this->container['error']) && !in_array($this->container['error'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'error', must be one of '%s'",
                $this->container['error'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets operation_succeeded
     *
     * @return bool|null
     */
    public function getOperationSucceeded()
    {
        return $this->container['operation_succeeded'];
    }

    /**
     * Sets operation_succeeded
     *
     * @param bool|null $operation_succeeded operation_succeeded
     *
     * @return self
     */
    public function setOperationSucceeded($operation_succeeded)
    {
        if (is_null($operation_succeeded)) {
            throw new \InvalidArgumentException('non-nullable operation_succeeded cannot be null');
        }
        $this->container['operation_succeeded'] = $operation_succeeded;

        return $this;
    }

    /**
     * Gets error
     *
     * @return int|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param int|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $allowedValues = $this->getErrorAllowableValues();
        if (!in_array($error, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'error', must be one of '%s'",
                    $error,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets error_text
     *
     * @return string|null
     */
    public function getErrorText()
    {
        return $this->container['error_text'];
    }

    /**
     * Sets error_text
     *
     * @param string|null $error_text error_text
     *
     * @return self
     */
    public function setErrorText($error_text)
    {
        if (is_null($error_text)) {
            throw new \InvalidArgumentException('non-nullable error_text cannot be null');
        }
        $this->container['error_text'] = $error_text;

        return $this;
    }

    /**
     * Gets product_type_code
     *
     * @return string|null
     */
    public function getProductTypeCode()
    {
        return $this->container['product_type_code'];
    }

    /**
     * Sets product_type_code
     *
     * @param string|null $product_type_code product_type_code
     *
     * @return self
     */
    public function setProductTypeCode($product_type_code)
    {
        if (is_null($product_type_code)) {
            throw new \InvalidArgumentException('non-nullable product_type_code cannot be null');
        }
        $this->container['product_type_code'] = $product_type_code;

        return $this;
    }

    /**
     * Gets product_code
     *
     * @return string|null
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     *
     * @param string|null $product_code product_code
     *
     * @return self
     */
    public function setProductCode($product_code)
    {
        if (is_null($product_code)) {
            throw new \InvalidArgumentException('non-nullable product_code cannot be null');
        }
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets provider_code
     *
     * @return string|null
     */
    public function getProviderCode()
    {
        return $this->container['provider_code'];
    }

    /**
     * Sets provider_code
     *
     * @param string|null $provider_code provider_code
     *
     * @return self
     */
    public function setProviderCode($provider_code)
    {
        if (is_null($provider_code)) {
            throw new \InvalidArgumentException('non-nullable provider_code cannot be null');
        }
        $this->container['provider_code'] = $provider_code;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \OpenAPI\Client\Model\AvailableCountries|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \OpenAPI\Client\Model\AvailableCountries|null $items items
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            throw new \InvalidArgumentException('non-nullable items cannot be null');
        }
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets visible_fields
     *
     * @return \OpenAPI\Client\Model\VisibleFields|null
     */
    public function getVisibleFields()
    {
        return $this->container['visible_fields'];
    }

    /**
     * Sets visible_fields
     *
     * @param \OpenAPI\Client\Model\VisibleFields|null $visible_fields visible_fields
     *
     * @return self
     */
    public function setVisibleFields($visible_fields)
    {
        if (is_null($visible_fields)) {
            throw new \InvalidArgumentException('non-nullable visible_fields cannot be null');
        }
        $this->container['visible_fields'] = $visible_fields;

        return $this;
    }

    /**
     * Gets mandatory_fields
     *
     * @return \OpenAPI\Client\Model\MandatoryFields|null
     */
    public function getMandatoryFields()
    {
        return $this->container['mandatory_fields'];
    }

    /**
     * Sets mandatory_fields
     *
     * @param \OpenAPI\Client\Model\MandatoryFields|null $mandatory_fields mandatory_fields
     *
     * @return self
     */
    public function setMandatoryFields($mandatory_fields)
    {
        if (is_null($mandatory_fields)) {
            throw new \InvalidArgumentException('non-nullable mandatory_fields cannot be null');
        }
        $this->container['mandatory_fields'] = $mandatory_fields;

        return $this;
    }

    /**
     * Gets next_method_call
     *
     * @return string|null
     */
    public function getNextMethodCall()
    {
        return $this->container['next_method_call'];
    }

    /**
     * Sets next_method_call
     *
     * @param string|null $next_method_call next_method_call
     *
     * @return self
     */
    public function setNextMethodCall($next_method_call)
    {
        if (is_null($next_method_call)) {
            throw new \InvalidArgumentException('non-nullable next_method_call cannot be null');
        }
        $this->container['next_method_call'] = $next_method_call;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


