<?php
/**
 * MandatoryFields
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MandatoryFields Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MandatoryFields implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MandatoryFields';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'token' => 'bool',
        'product_type_code' => 'bool',
        'provider_code' => 'bool',
        'product_code' => 'bool',
        'product_option_code' => 'bool',
        'external_reference' => 'bool',
        'entity' => 'bool',
        'reference' => 'bool',
        'complete_reference' => 'bool',
        'amount' => 'bool',
        'invoice_customer_name' => 'bool',
        'invoice_customer_vat_number' => 'bool',
        'customer_name' => 'bool',
        'customer_id_number' => 'bool',
        'customer_phone' => 'bool',
        'customer_email' => 'bool',
        'quantity' => 'bool',
        'search_text' => 'bool',
        'event_id' => 'bool',
        'session_type_id' => 'bool',
        'session_id' => 'bool',
        'sector_id' => 'bool',
        'session_sector_id' => 'bool',
        'vat_rate' => 'bool',
        'vgp_code' => 'bool',
        'vfp_code' => 'bool',
        'general_data_message' => 'bool',
        'recharge_bonus' => 'bool',
        'recharge_bonus_percent' => 'bool',
        'recharge_cost' => 'bool',
        'vality_period' => 'bool',
        'recharge_value_catagory_description' => 'bool',
        'vality_period_bonus' => 'bool',
        'message' => 'bool',
        'recharge_value_key' => 'bool',
        'recharge_bonus_category_description' => 'bool',
        'branch_code' => 'bool',
        'recharge_value_code' => 'bool',
        'dealer_code' => 'bool',
        'group_code' => 'bool',
        'transaction_id' => 'bool',
        'accept_up_sell' => 'bool',
        'up_sell_message' => 'bool',
        'up_sell_amount' => 'bool',
        'country_code' => 'bool',
        'operator_code' => 'bool',
        'group_key' => 'bool',
        'operator_name' => 'bool',
        'customer_care_number' => 'bool',
        'country_name' => 'bool',
        'cpf' => 'bool',
        'send_value' => 'bool',
        'receive_value' => 'bool',
        'receive_currency_iso' => 'bool',
        'send_currency_iso' => 'bool',
        'receive_value_excluding_tax' => 'bool',
        'tax_rate' => 'bool',
        'tax_name' => 'bool',
        'tax_calculation' => 'bool',
        'customer_fee' => 'bool',
        'distributor_fee' => 'bool',
        'commission_rate' => 'bool',
        'processing_mode' => 'bool',
        'redemption_mechanism' => 'bool',
        'sku_code' => 'bool',
        'localization_key' => 'bool',
        'additional_information' => 'bool',
        'default_display_text' => 'bool',
        'settings' => 'bool',
        'charge_value' => 'bool',
        'charge_currency_iso' => 'bool',
        'client_ip' => 'bool',
        'user_id' => 'bool',
        'zone_id' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'token' => null,
        'product_type_code' => null,
        'provider_code' => null,
        'product_code' => null,
        'product_option_code' => null,
        'external_reference' => null,
        'entity' => null,
        'reference' => null,
        'complete_reference' => null,
        'amount' => null,
        'invoice_customer_name' => null,
        'invoice_customer_vat_number' => null,
        'customer_name' => null,
        'customer_id_number' => null,
        'customer_phone' => null,
        'customer_email' => null,
        'quantity' => null,
        'search_text' => null,
        'event_id' => null,
        'session_type_id' => null,
        'session_id' => null,
        'sector_id' => null,
        'session_sector_id' => null,
        'vat_rate' => null,
        'vgp_code' => null,
        'vfp_code' => null,
        'general_data_message' => null,
        'recharge_bonus' => null,
        'recharge_bonus_percent' => null,
        'recharge_cost' => null,
        'vality_period' => null,
        'recharge_value_catagory_description' => null,
        'vality_period_bonus' => null,
        'message' => null,
        'recharge_value_key' => null,
        'recharge_bonus_category_description' => null,
        'branch_code' => null,
        'recharge_value_code' => null,
        'dealer_code' => null,
        'group_code' => null,
        'transaction_id' => null,
        'accept_up_sell' => null,
        'up_sell_message' => null,
        'up_sell_amount' => null,
        'country_code' => null,
        'operator_code' => null,
        'group_key' => null,
        'operator_name' => null,
        'customer_care_number' => null,
        'country_name' => null,
        'cpf' => null,
        'send_value' => null,
        'receive_value' => null,
        'receive_currency_iso' => null,
        'send_currency_iso' => null,
        'receive_value_excluding_tax' => null,
        'tax_rate' => null,
        'tax_name' => null,
        'tax_calculation' => null,
        'customer_fee' => null,
        'distributor_fee' => null,
        'commission_rate' => null,
        'processing_mode' => null,
        'redemption_mechanism' => null,
        'sku_code' => null,
        'localization_key' => null,
        'additional_information' => null,
        'default_display_text' => null,
        'settings' => null,
        'charge_value' => null,
        'charge_currency_iso' => null,
        'client_ip' => null,
        'user_id' => null,
        'zone_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'token' => false,
        'product_type_code' => false,
        'provider_code' => false,
        'product_code' => false,
        'product_option_code' => false,
        'external_reference' => false,
        'entity' => false,
        'reference' => false,
        'complete_reference' => false,
        'amount' => false,
        'invoice_customer_name' => false,
        'invoice_customer_vat_number' => false,
        'customer_name' => false,
        'customer_id_number' => false,
        'customer_phone' => false,
        'customer_email' => false,
        'quantity' => false,
        'search_text' => false,
        'event_id' => false,
        'session_type_id' => false,
        'session_id' => false,
        'sector_id' => false,
        'session_sector_id' => false,
        'vat_rate' => false,
        'vgp_code' => false,
        'vfp_code' => false,
        'general_data_message' => false,
        'recharge_bonus' => false,
        'recharge_bonus_percent' => false,
        'recharge_cost' => false,
        'vality_period' => false,
        'recharge_value_catagory_description' => false,
        'vality_period_bonus' => false,
        'message' => false,
        'recharge_value_key' => false,
        'recharge_bonus_category_description' => false,
        'branch_code' => false,
        'recharge_value_code' => false,
        'dealer_code' => false,
        'group_code' => false,
        'transaction_id' => false,
        'accept_up_sell' => false,
        'up_sell_message' => false,
        'up_sell_amount' => false,
        'country_code' => false,
        'operator_code' => false,
        'group_key' => false,
        'operator_name' => false,
        'customer_care_number' => false,
        'country_name' => false,
        'cpf' => false,
        'send_value' => false,
        'receive_value' => false,
        'receive_currency_iso' => false,
        'send_currency_iso' => false,
        'receive_value_excluding_tax' => false,
        'tax_rate' => false,
        'tax_name' => false,
        'tax_calculation' => false,
        'customer_fee' => false,
        'distributor_fee' => false,
        'commission_rate' => false,
        'processing_mode' => false,
        'redemption_mechanism' => false,
        'sku_code' => false,
        'localization_key' => false,
        'additional_information' => false,
        'default_display_text' => false,
        'settings' => false,
        'charge_value' => false,
        'charge_currency_iso' => false,
        'client_ip' => false,
        'user_id' => false,
        'zone_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'token' => 'Token',
        'product_type_code' => 'ProductTypeCode',
        'provider_code' => 'ProviderCode',
        'product_code' => 'ProductCode',
        'product_option_code' => 'ProductOptionCode',
        'external_reference' => 'ExternalReference',
        'entity' => 'Entity',
        'reference' => 'Reference',
        'complete_reference' => 'CompleteReference',
        'amount' => 'Amount',
        'invoice_customer_name' => 'InvoiceCustomerName',
        'invoice_customer_vat_number' => 'InvoiceCustomerVatNumber',
        'customer_name' => 'CustomerName',
        'customer_id_number' => 'CustomerIdNumber',
        'customer_phone' => 'CustomerPhone',
        'customer_email' => 'CustomerEmail',
        'quantity' => 'Quantity',
        'search_text' => 'SearchText',
        'event_id' => 'EventId',
        'session_type_id' => 'SessionTypeId',
        'session_id' => 'SessionId',
        'sector_id' => 'SectorId',
        'session_sector_id' => 'SessionSectorId',
        'vat_rate' => 'VatRate',
        'vgp_code' => 'VGPCode',
        'vfp_code' => 'VFPCode',
        'general_data_message' => 'GeneralDataMessage',
        'recharge_bonus' => 'RechargeBonus',
        'recharge_bonus_percent' => 'RechargeBonusPercent',
        'recharge_cost' => 'RechargeCost',
        'vality_period' => 'ValityPeriod',
        'recharge_value_catagory_description' => 'RechargeValueCatagoryDescription',
        'vality_period_bonus' => 'ValityPeriodBonus',
        'message' => 'Message',
        'recharge_value_key' => 'RechargeValueKey',
        'recharge_bonus_category_description' => 'RechargeBonusCategoryDescription',
        'branch_code' => 'BranchCode',
        'recharge_value_code' => 'RechargeValueCode',
        'dealer_code' => 'DealerCode',
        'group_code' => 'GroupCode',
        'transaction_id' => 'TransactionId',
        'accept_up_sell' => 'AcceptUpSell',
        'up_sell_message' => 'UpSellMessage',
        'up_sell_amount' => 'UpSellAmount',
        'country_code' => 'CountryCode',
        'operator_code' => 'OperatorCode',
        'group_key' => 'GroupKey',
        'operator_name' => 'OperatorName',
        'customer_care_number' => 'CustomerCareNumber',
        'country_name' => 'CountryName',
        'cpf' => 'CPF',
        'send_value' => 'SendValue',
        'receive_value' => 'ReceiveValue',
        'receive_currency_iso' => 'ReceiveCurrencyIso',
        'send_currency_iso' => 'SendCurrencyIso',
        'receive_value_excluding_tax' => 'ReceiveValueExcludingTax',
        'tax_rate' => 'TaxRate',
        'tax_name' => 'TaxName',
        'tax_calculation' => 'TaxCalculation',
        'customer_fee' => 'CustomerFee',
        'distributor_fee' => 'DistributorFee',
        'commission_rate' => 'CommissionRate',
        'processing_mode' => 'ProcessingMode',
        'redemption_mechanism' => 'RedemptionMechanism',
        'sku_code' => 'SkuCode',
        'localization_key' => 'LocalizationKey',
        'additional_information' => 'AdditionalInformation',
        'default_display_text' => 'DefaultDisplayText',
        'settings' => 'Settings',
        'charge_value' => 'ChargeValue',
        'charge_currency_iso' => 'ChargeCurrencyIso',
        'client_ip' => 'ClientIp',
        'user_id' => 'UserId',
        'zone_id' => 'ZoneId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'token' => 'setToken',
        'product_type_code' => 'setProductTypeCode',
        'provider_code' => 'setProviderCode',
        'product_code' => 'setProductCode',
        'product_option_code' => 'setProductOptionCode',
        'external_reference' => 'setExternalReference',
        'entity' => 'setEntity',
        'reference' => 'setReference',
        'complete_reference' => 'setCompleteReference',
        'amount' => 'setAmount',
        'invoice_customer_name' => 'setInvoiceCustomerName',
        'invoice_customer_vat_number' => 'setInvoiceCustomerVatNumber',
        'customer_name' => 'setCustomerName',
        'customer_id_number' => 'setCustomerIdNumber',
        'customer_phone' => 'setCustomerPhone',
        'customer_email' => 'setCustomerEmail',
        'quantity' => 'setQuantity',
        'search_text' => 'setSearchText',
        'event_id' => 'setEventId',
        'session_type_id' => 'setSessionTypeId',
        'session_id' => 'setSessionId',
        'sector_id' => 'setSectorId',
        'session_sector_id' => 'setSessionSectorId',
        'vat_rate' => 'setVatRate',
        'vgp_code' => 'setVgpCode',
        'vfp_code' => 'setVfpCode',
        'general_data_message' => 'setGeneralDataMessage',
        'recharge_bonus' => 'setRechargeBonus',
        'recharge_bonus_percent' => 'setRechargeBonusPercent',
        'recharge_cost' => 'setRechargeCost',
        'vality_period' => 'setValityPeriod',
        'recharge_value_catagory_description' => 'setRechargeValueCatagoryDescription',
        'vality_period_bonus' => 'setValityPeriodBonus',
        'message' => 'setMessage',
        'recharge_value_key' => 'setRechargeValueKey',
        'recharge_bonus_category_description' => 'setRechargeBonusCategoryDescription',
        'branch_code' => 'setBranchCode',
        'recharge_value_code' => 'setRechargeValueCode',
        'dealer_code' => 'setDealerCode',
        'group_code' => 'setGroupCode',
        'transaction_id' => 'setTransactionId',
        'accept_up_sell' => 'setAcceptUpSell',
        'up_sell_message' => 'setUpSellMessage',
        'up_sell_amount' => 'setUpSellAmount',
        'country_code' => 'setCountryCode',
        'operator_code' => 'setOperatorCode',
        'group_key' => 'setGroupKey',
        'operator_name' => 'setOperatorName',
        'customer_care_number' => 'setCustomerCareNumber',
        'country_name' => 'setCountryName',
        'cpf' => 'setCpf',
        'send_value' => 'setSendValue',
        'receive_value' => 'setReceiveValue',
        'receive_currency_iso' => 'setReceiveCurrencyIso',
        'send_currency_iso' => 'setSendCurrencyIso',
        'receive_value_excluding_tax' => 'setReceiveValueExcludingTax',
        'tax_rate' => 'setTaxRate',
        'tax_name' => 'setTaxName',
        'tax_calculation' => 'setTaxCalculation',
        'customer_fee' => 'setCustomerFee',
        'distributor_fee' => 'setDistributorFee',
        'commission_rate' => 'setCommissionRate',
        'processing_mode' => 'setProcessingMode',
        'redemption_mechanism' => 'setRedemptionMechanism',
        'sku_code' => 'setSkuCode',
        'localization_key' => 'setLocalizationKey',
        'additional_information' => 'setAdditionalInformation',
        'default_display_text' => 'setDefaultDisplayText',
        'settings' => 'setSettings',
        'charge_value' => 'setChargeValue',
        'charge_currency_iso' => 'setChargeCurrencyIso',
        'client_ip' => 'setClientIp',
        'user_id' => 'setUserId',
        'zone_id' => 'setZoneId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'token' => 'getToken',
        'product_type_code' => 'getProductTypeCode',
        'provider_code' => 'getProviderCode',
        'product_code' => 'getProductCode',
        'product_option_code' => 'getProductOptionCode',
        'external_reference' => 'getExternalReference',
        'entity' => 'getEntity',
        'reference' => 'getReference',
        'complete_reference' => 'getCompleteReference',
        'amount' => 'getAmount',
        'invoice_customer_name' => 'getInvoiceCustomerName',
        'invoice_customer_vat_number' => 'getInvoiceCustomerVatNumber',
        'customer_name' => 'getCustomerName',
        'customer_id_number' => 'getCustomerIdNumber',
        'customer_phone' => 'getCustomerPhone',
        'customer_email' => 'getCustomerEmail',
        'quantity' => 'getQuantity',
        'search_text' => 'getSearchText',
        'event_id' => 'getEventId',
        'session_type_id' => 'getSessionTypeId',
        'session_id' => 'getSessionId',
        'sector_id' => 'getSectorId',
        'session_sector_id' => 'getSessionSectorId',
        'vat_rate' => 'getVatRate',
        'vgp_code' => 'getVgpCode',
        'vfp_code' => 'getVfpCode',
        'general_data_message' => 'getGeneralDataMessage',
        'recharge_bonus' => 'getRechargeBonus',
        'recharge_bonus_percent' => 'getRechargeBonusPercent',
        'recharge_cost' => 'getRechargeCost',
        'vality_period' => 'getValityPeriod',
        'recharge_value_catagory_description' => 'getRechargeValueCatagoryDescription',
        'vality_period_bonus' => 'getValityPeriodBonus',
        'message' => 'getMessage',
        'recharge_value_key' => 'getRechargeValueKey',
        'recharge_bonus_category_description' => 'getRechargeBonusCategoryDescription',
        'branch_code' => 'getBranchCode',
        'recharge_value_code' => 'getRechargeValueCode',
        'dealer_code' => 'getDealerCode',
        'group_code' => 'getGroupCode',
        'transaction_id' => 'getTransactionId',
        'accept_up_sell' => 'getAcceptUpSell',
        'up_sell_message' => 'getUpSellMessage',
        'up_sell_amount' => 'getUpSellAmount',
        'country_code' => 'getCountryCode',
        'operator_code' => 'getOperatorCode',
        'group_key' => 'getGroupKey',
        'operator_name' => 'getOperatorName',
        'customer_care_number' => 'getCustomerCareNumber',
        'country_name' => 'getCountryName',
        'cpf' => 'getCpf',
        'send_value' => 'getSendValue',
        'receive_value' => 'getReceiveValue',
        'receive_currency_iso' => 'getReceiveCurrencyIso',
        'send_currency_iso' => 'getSendCurrencyIso',
        'receive_value_excluding_tax' => 'getReceiveValueExcludingTax',
        'tax_rate' => 'getTaxRate',
        'tax_name' => 'getTaxName',
        'tax_calculation' => 'getTaxCalculation',
        'customer_fee' => 'getCustomerFee',
        'distributor_fee' => 'getDistributorFee',
        'commission_rate' => 'getCommissionRate',
        'processing_mode' => 'getProcessingMode',
        'redemption_mechanism' => 'getRedemptionMechanism',
        'sku_code' => 'getSkuCode',
        'localization_key' => 'getLocalizationKey',
        'additional_information' => 'getAdditionalInformation',
        'default_display_text' => 'getDefaultDisplayText',
        'settings' => 'getSettings',
        'charge_value' => 'getChargeValue',
        'charge_currency_iso' => 'getChargeCurrencyIso',
        'client_ip' => 'getClientIp',
        'user_id' => 'getUserId',
        'zone_id' => 'getZoneId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('product_type_code', $data ?? [], null);
        $this->setIfExists('provider_code', $data ?? [], null);
        $this->setIfExists('product_code', $data ?? [], null);
        $this->setIfExists('product_option_code', $data ?? [], null);
        $this->setIfExists('external_reference', $data ?? [], null);
        $this->setIfExists('entity', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('complete_reference', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('invoice_customer_name', $data ?? [], null);
        $this->setIfExists('invoice_customer_vat_number', $data ?? [], null);
        $this->setIfExists('customer_name', $data ?? [], null);
        $this->setIfExists('customer_id_number', $data ?? [], null);
        $this->setIfExists('customer_phone', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('search_text', $data ?? [], null);
        $this->setIfExists('event_id', $data ?? [], null);
        $this->setIfExists('session_type_id', $data ?? [], null);
        $this->setIfExists('session_id', $data ?? [], null);
        $this->setIfExists('sector_id', $data ?? [], null);
        $this->setIfExists('session_sector_id', $data ?? [], null);
        $this->setIfExists('vat_rate', $data ?? [], null);
        $this->setIfExists('vgp_code', $data ?? [], null);
        $this->setIfExists('vfp_code', $data ?? [], null);
        $this->setIfExists('general_data_message', $data ?? [], null);
        $this->setIfExists('recharge_bonus', $data ?? [], null);
        $this->setIfExists('recharge_bonus_percent', $data ?? [], null);
        $this->setIfExists('recharge_cost', $data ?? [], null);
        $this->setIfExists('vality_period', $data ?? [], null);
        $this->setIfExists('recharge_value_catagory_description', $data ?? [], null);
        $this->setIfExists('vality_period_bonus', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('recharge_value_key', $data ?? [], null);
        $this->setIfExists('recharge_bonus_category_description', $data ?? [], null);
        $this->setIfExists('branch_code', $data ?? [], null);
        $this->setIfExists('recharge_value_code', $data ?? [], null);
        $this->setIfExists('dealer_code', $data ?? [], null);
        $this->setIfExists('group_code', $data ?? [], null);
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('accept_up_sell', $data ?? [], null);
        $this->setIfExists('up_sell_message', $data ?? [], null);
        $this->setIfExists('up_sell_amount', $data ?? [], null);
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('operator_code', $data ?? [], null);
        $this->setIfExists('group_key', $data ?? [], null);
        $this->setIfExists('operator_name', $data ?? [], null);
        $this->setIfExists('customer_care_number', $data ?? [], null);
        $this->setIfExists('country_name', $data ?? [], null);
        $this->setIfExists('cpf', $data ?? [], null);
        $this->setIfExists('send_value', $data ?? [], null);
        $this->setIfExists('receive_value', $data ?? [], null);
        $this->setIfExists('receive_currency_iso', $data ?? [], null);
        $this->setIfExists('send_currency_iso', $data ?? [], null);
        $this->setIfExists('receive_value_excluding_tax', $data ?? [], null);
        $this->setIfExists('tax_rate', $data ?? [], null);
        $this->setIfExists('tax_name', $data ?? [], null);
        $this->setIfExists('tax_calculation', $data ?? [], null);
        $this->setIfExists('customer_fee', $data ?? [], null);
        $this->setIfExists('distributor_fee', $data ?? [], null);
        $this->setIfExists('commission_rate', $data ?? [], null);
        $this->setIfExists('processing_mode', $data ?? [], null);
        $this->setIfExists('redemption_mechanism', $data ?? [], null);
        $this->setIfExists('sku_code', $data ?? [], null);
        $this->setIfExists('localization_key', $data ?? [], null);
        $this->setIfExists('additional_information', $data ?? [], null);
        $this->setIfExists('default_display_text', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
        $this->setIfExists('charge_value', $data ?? [], null);
        $this->setIfExists('charge_currency_iso', $data ?? [], null);
        $this->setIfExists('client_ip', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('zone_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets token
     *
     * @return bool|null
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param bool|null $token token
     *
     * @return self
     */
    public function setToken($token)
    {
        if (is_null($token)) {
            throw new \InvalidArgumentException('non-nullable token cannot be null');
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets product_type_code
     *
     * @return bool|null
     */
    public function getProductTypeCode()
    {
        return $this->container['product_type_code'];
    }

    /**
     * Sets product_type_code
     *
     * @param bool|null $product_type_code product_type_code
     *
     * @return self
     */
    public function setProductTypeCode($product_type_code)
    {
        if (is_null($product_type_code)) {
            throw new \InvalidArgumentException('non-nullable product_type_code cannot be null');
        }
        $this->container['product_type_code'] = $product_type_code;

        return $this;
    }

    /**
     * Gets provider_code
     *
     * @return bool|null
     */
    public function getProviderCode()
    {
        return $this->container['provider_code'];
    }

    /**
     * Sets provider_code
     *
     * @param bool|null $provider_code provider_code
     *
     * @return self
     */
    public function setProviderCode($provider_code)
    {
        if (is_null($provider_code)) {
            throw new \InvalidArgumentException('non-nullable provider_code cannot be null');
        }
        $this->container['provider_code'] = $provider_code;

        return $this;
    }

    /**
     * Gets product_code
     *
     * @return bool|null
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     *
     * @param bool|null $product_code product_code
     *
     * @return self
     */
    public function setProductCode($product_code)
    {
        if (is_null($product_code)) {
            throw new \InvalidArgumentException('non-nullable product_code cannot be null');
        }
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets product_option_code
     *
     * @return bool|null
     */
    public function getProductOptionCode()
    {
        return $this->container['product_option_code'];
    }

    /**
     * Sets product_option_code
     *
     * @param bool|null $product_option_code product_option_code
     *
     * @return self
     */
    public function setProductOptionCode($product_option_code)
    {
        if (is_null($product_option_code)) {
            throw new \InvalidArgumentException('non-nullable product_option_code cannot be null');
        }
        $this->container['product_option_code'] = $product_option_code;

        return $this;
    }

    /**
     * Gets external_reference
     *
     * @return bool|null
     */
    public function getExternalReference()
    {
        return $this->container['external_reference'];
    }

    /**
     * Sets external_reference
     *
     * @param bool|null $external_reference external_reference
     *
     * @return self
     */
    public function setExternalReference($external_reference)
    {
        if (is_null($external_reference)) {
            throw new \InvalidArgumentException('non-nullable external_reference cannot be null');
        }
        $this->container['external_reference'] = $external_reference;

        return $this;
    }

    /**
     * Gets entity
     *
     * @return bool|null
     */
    public function getEntity()
    {
        return $this->container['entity'];
    }

    /**
     * Sets entity
     *
     * @param bool|null $entity entity
     *
     * @return self
     */
    public function setEntity($entity)
    {
        if (is_null($entity)) {
            throw new \InvalidArgumentException('non-nullable entity cannot be null');
        }
        $this->container['entity'] = $entity;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return bool|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param bool|null $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets complete_reference
     *
     * @return bool|null
     */
    public function getCompleteReference()
    {
        return $this->container['complete_reference'];
    }

    /**
     * Sets complete_reference
     *
     * @param bool|null $complete_reference complete_reference
     *
     * @return self
     */
    public function setCompleteReference($complete_reference)
    {
        if (is_null($complete_reference)) {
            throw new \InvalidArgumentException('non-nullable complete_reference cannot be null');
        }
        $this->container['complete_reference'] = $complete_reference;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return bool|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param bool|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets invoice_customer_name
     *
     * @return bool|null
     */
    public function getInvoiceCustomerName()
    {
        return $this->container['invoice_customer_name'];
    }

    /**
     * Sets invoice_customer_name
     *
     * @param bool|null $invoice_customer_name invoice_customer_name
     *
     * @return self
     */
    public function setInvoiceCustomerName($invoice_customer_name)
    {
        if (is_null($invoice_customer_name)) {
            throw new \InvalidArgumentException('non-nullable invoice_customer_name cannot be null');
        }
        $this->container['invoice_customer_name'] = $invoice_customer_name;

        return $this;
    }

    /**
     * Gets invoice_customer_vat_number
     *
     * @return bool|null
     */
    public function getInvoiceCustomerVatNumber()
    {
        return $this->container['invoice_customer_vat_number'];
    }

    /**
     * Sets invoice_customer_vat_number
     *
     * @param bool|null $invoice_customer_vat_number invoice_customer_vat_number
     *
     * @return self
     */
    public function setInvoiceCustomerVatNumber($invoice_customer_vat_number)
    {
        if (is_null($invoice_customer_vat_number)) {
            throw new \InvalidArgumentException('non-nullable invoice_customer_vat_number cannot be null');
        }
        $this->container['invoice_customer_vat_number'] = $invoice_customer_vat_number;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return bool|null
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param bool|null $customer_name customer_name
     *
     * @return self
     */
    public function setCustomerName($customer_name)
    {
        if (is_null($customer_name)) {
            throw new \InvalidArgumentException('non-nullable customer_name cannot be null');
        }
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets customer_id_number
     *
     * @return bool|null
     */
    public function getCustomerIdNumber()
    {
        return $this->container['customer_id_number'];
    }

    /**
     * Sets customer_id_number
     *
     * @param bool|null $customer_id_number customer_id_number
     *
     * @return self
     */
    public function setCustomerIdNumber($customer_id_number)
    {
        if (is_null($customer_id_number)) {
            throw new \InvalidArgumentException('non-nullable customer_id_number cannot be null');
        }
        $this->container['customer_id_number'] = $customer_id_number;

        return $this;
    }

    /**
     * Gets customer_phone
     *
     * @return bool|null
     */
    public function getCustomerPhone()
    {
        return $this->container['customer_phone'];
    }

    /**
     * Sets customer_phone
     *
     * @param bool|null $customer_phone customer_phone
     *
     * @return self
     */
    public function setCustomerPhone($customer_phone)
    {
        if (is_null($customer_phone)) {
            throw new \InvalidArgumentException('non-nullable customer_phone cannot be null');
        }
        $this->container['customer_phone'] = $customer_phone;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return bool|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param bool|null $customer_email customer_email
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            throw new \InvalidArgumentException('non-nullable customer_email cannot be null');
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return bool|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param bool|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets search_text
     *
     * @return bool|null
     */
    public function getSearchText()
    {
        return $this->container['search_text'];
    }

    /**
     * Sets search_text
     *
     * @param bool|null $search_text search_text
     *
     * @return self
     */
    public function setSearchText($search_text)
    {
        if (is_null($search_text)) {
            throw new \InvalidArgumentException('non-nullable search_text cannot be null');
        }
        $this->container['search_text'] = $search_text;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return bool|null
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param bool|null $event_id event_id
     *
     * @return self
     */
    public function setEventId($event_id)
    {
        if (is_null($event_id)) {
            throw new \InvalidArgumentException('non-nullable event_id cannot be null');
        }
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets session_type_id
     *
     * @return bool|null
     */
    public function getSessionTypeId()
    {
        return $this->container['session_type_id'];
    }

    /**
     * Sets session_type_id
     *
     * @param bool|null $session_type_id session_type_id
     *
     * @return self
     */
    public function setSessionTypeId($session_type_id)
    {
        if (is_null($session_type_id)) {
            throw new \InvalidArgumentException('non-nullable session_type_id cannot be null');
        }
        $this->container['session_type_id'] = $session_type_id;

        return $this;
    }

    /**
     * Gets session_id
     *
     * @return bool|null
     */
    public function getSessionId()
    {
        return $this->container['session_id'];
    }

    /**
     * Sets session_id
     *
     * @param bool|null $session_id session_id
     *
     * @return self
     */
    public function setSessionId($session_id)
    {
        if (is_null($session_id)) {
            throw new \InvalidArgumentException('non-nullable session_id cannot be null');
        }
        $this->container['session_id'] = $session_id;

        return $this;
    }

    /**
     * Gets sector_id
     *
     * @return bool|null
     */
    public function getSectorId()
    {
        return $this->container['sector_id'];
    }

    /**
     * Sets sector_id
     *
     * @param bool|null $sector_id sector_id
     *
     * @return self
     */
    public function setSectorId($sector_id)
    {
        if (is_null($sector_id)) {
            throw new \InvalidArgumentException('non-nullable sector_id cannot be null');
        }
        $this->container['sector_id'] = $sector_id;

        return $this;
    }

    /**
     * Gets session_sector_id
     *
     * @return bool|null
     */
    public function getSessionSectorId()
    {
        return $this->container['session_sector_id'];
    }

    /**
     * Sets session_sector_id
     *
     * @param bool|null $session_sector_id session_sector_id
     *
     * @return self
     */
    public function setSessionSectorId($session_sector_id)
    {
        if (is_null($session_sector_id)) {
            throw new \InvalidArgumentException('non-nullable session_sector_id cannot be null');
        }
        $this->container['session_sector_id'] = $session_sector_id;

        return $this;
    }

    /**
     * Gets vat_rate
     *
     * @return bool|null
     */
    public function getVatRate()
    {
        return $this->container['vat_rate'];
    }

    /**
     * Sets vat_rate
     *
     * @param bool|null $vat_rate vat_rate
     *
     * @return self
     */
    public function setVatRate($vat_rate)
    {
        if (is_null($vat_rate)) {
            throw new \InvalidArgumentException('non-nullable vat_rate cannot be null');
        }
        $this->container['vat_rate'] = $vat_rate;

        return $this;
    }

    /**
     * Gets vgp_code
     *
     * @return bool|null
     */
    public function getVgpCode()
    {
        return $this->container['vgp_code'];
    }

    /**
     * Sets vgp_code
     *
     * @param bool|null $vgp_code vgp_code
     *
     * @return self
     */
    public function setVgpCode($vgp_code)
    {
        if (is_null($vgp_code)) {
            throw new \InvalidArgumentException('non-nullable vgp_code cannot be null');
        }
        $this->container['vgp_code'] = $vgp_code;

        return $this;
    }

    /**
     * Gets vfp_code
     *
     * @return bool|null
     */
    public function getVfpCode()
    {
        return $this->container['vfp_code'];
    }

    /**
     * Sets vfp_code
     *
     * @param bool|null $vfp_code vfp_code
     *
     * @return self
     */
    public function setVfpCode($vfp_code)
    {
        if (is_null($vfp_code)) {
            throw new \InvalidArgumentException('non-nullable vfp_code cannot be null');
        }
        $this->container['vfp_code'] = $vfp_code;

        return $this;
    }

    /**
     * Gets general_data_message
     *
     * @return bool|null
     */
    public function getGeneralDataMessage()
    {
        return $this->container['general_data_message'];
    }

    /**
     * Sets general_data_message
     *
     * @param bool|null $general_data_message general_data_message
     *
     * @return self
     */
    public function setGeneralDataMessage($general_data_message)
    {
        if (is_null($general_data_message)) {
            throw new \InvalidArgumentException('non-nullable general_data_message cannot be null');
        }
        $this->container['general_data_message'] = $general_data_message;

        return $this;
    }

    /**
     * Gets recharge_bonus
     *
     * @return bool|null
     */
    public function getRechargeBonus()
    {
        return $this->container['recharge_bonus'];
    }

    /**
     * Sets recharge_bonus
     *
     * @param bool|null $recharge_bonus recharge_bonus
     *
     * @return self
     */
    public function setRechargeBonus($recharge_bonus)
    {
        if (is_null($recharge_bonus)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus cannot be null');
        }
        $this->container['recharge_bonus'] = $recharge_bonus;

        return $this;
    }

    /**
     * Gets recharge_bonus_percent
     *
     * @return bool|null
     */
    public function getRechargeBonusPercent()
    {
        return $this->container['recharge_bonus_percent'];
    }

    /**
     * Sets recharge_bonus_percent
     *
     * @param bool|null $recharge_bonus_percent recharge_bonus_percent
     *
     * @return self
     */
    public function setRechargeBonusPercent($recharge_bonus_percent)
    {
        if (is_null($recharge_bonus_percent)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus_percent cannot be null');
        }
        $this->container['recharge_bonus_percent'] = $recharge_bonus_percent;

        return $this;
    }

    /**
     * Gets recharge_cost
     *
     * @return bool|null
     */
    public function getRechargeCost()
    {
        return $this->container['recharge_cost'];
    }

    /**
     * Sets recharge_cost
     *
     * @param bool|null $recharge_cost recharge_cost
     *
     * @return self
     */
    public function setRechargeCost($recharge_cost)
    {
        if (is_null($recharge_cost)) {
            throw new \InvalidArgumentException('non-nullable recharge_cost cannot be null');
        }
        $this->container['recharge_cost'] = $recharge_cost;

        return $this;
    }

    /**
     * Gets vality_period
     *
     * @return bool|null
     */
    public function getValityPeriod()
    {
        return $this->container['vality_period'];
    }

    /**
     * Sets vality_period
     *
     * @param bool|null $vality_period vality_period
     *
     * @return self
     */
    public function setValityPeriod($vality_period)
    {
        if (is_null($vality_period)) {
            throw new \InvalidArgumentException('non-nullable vality_period cannot be null');
        }
        $this->container['vality_period'] = $vality_period;

        return $this;
    }

    /**
     * Gets recharge_value_catagory_description
     *
     * @return bool|null
     */
    public function getRechargeValueCatagoryDescription()
    {
        return $this->container['recharge_value_catagory_description'];
    }

    /**
     * Sets recharge_value_catagory_description
     *
     * @param bool|null $recharge_value_catagory_description recharge_value_catagory_description
     *
     * @return self
     */
    public function setRechargeValueCatagoryDescription($recharge_value_catagory_description)
    {
        if (is_null($recharge_value_catagory_description)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_catagory_description cannot be null');
        }
        $this->container['recharge_value_catagory_description'] = $recharge_value_catagory_description;

        return $this;
    }

    /**
     * Gets vality_period_bonus
     *
     * @return bool|null
     */
    public function getValityPeriodBonus()
    {
        return $this->container['vality_period_bonus'];
    }

    /**
     * Sets vality_period_bonus
     *
     * @param bool|null $vality_period_bonus vality_period_bonus
     *
     * @return self
     */
    public function setValityPeriodBonus($vality_period_bonus)
    {
        if (is_null($vality_period_bonus)) {
            throw new \InvalidArgumentException('non-nullable vality_period_bonus cannot be null');
        }
        $this->container['vality_period_bonus'] = $vality_period_bonus;

        return $this;
    }

    /**
     * Gets message
     *
     * @return bool|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param bool|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets recharge_value_key
     *
     * @return bool|null
     */
    public function getRechargeValueKey()
    {
        return $this->container['recharge_value_key'];
    }

    /**
     * Sets recharge_value_key
     *
     * @param bool|null $recharge_value_key recharge_value_key
     *
     * @return self
     */
    public function setRechargeValueKey($recharge_value_key)
    {
        if (is_null($recharge_value_key)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_key cannot be null');
        }
        $this->container['recharge_value_key'] = $recharge_value_key;

        return $this;
    }

    /**
     * Gets recharge_bonus_category_description
     *
     * @return bool|null
     */
    public function getRechargeBonusCategoryDescription()
    {
        return $this->container['recharge_bonus_category_description'];
    }

    /**
     * Sets recharge_bonus_category_description
     *
     * @param bool|null $recharge_bonus_category_description recharge_bonus_category_description
     *
     * @return self
     */
    public function setRechargeBonusCategoryDescription($recharge_bonus_category_description)
    {
        if (is_null($recharge_bonus_category_description)) {
            throw new \InvalidArgumentException('non-nullable recharge_bonus_category_description cannot be null');
        }
        $this->container['recharge_bonus_category_description'] = $recharge_bonus_category_description;

        return $this;
    }

    /**
     * Gets branch_code
     *
     * @return bool|null
     */
    public function getBranchCode()
    {
        return $this->container['branch_code'];
    }

    /**
     * Sets branch_code
     *
     * @param bool|null $branch_code branch_code
     *
     * @return self
     */
    public function setBranchCode($branch_code)
    {
        if (is_null($branch_code)) {
            throw new \InvalidArgumentException('non-nullable branch_code cannot be null');
        }
        $this->container['branch_code'] = $branch_code;

        return $this;
    }

    /**
     * Gets recharge_value_code
     *
     * @return bool|null
     */
    public function getRechargeValueCode()
    {
        return $this->container['recharge_value_code'];
    }

    /**
     * Sets recharge_value_code
     *
     * @param bool|null $recharge_value_code recharge_value_code
     *
     * @return self
     */
    public function setRechargeValueCode($recharge_value_code)
    {
        if (is_null($recharge_value_code)) {
            throw new \InvalidArgumentException('non-nullable recharge_value_code cannot be null');
        }
        $this->container['recharge_value_code'] = $recharge_value_code;

        return $this;
    }

    /**
     * Gets dealer_code
     *
     * @return bool|null
     */
    public function getDealerCode()
    {
        return $this->container['dealer_code'];
    }

    /**
     * Sets dealer_code
     *
     * @param bool|null $dealer_code dealer_code
     *
     * @return self
     */
    public function setDealerCode($dealer_code)
    {
        if (is_null($dealer_code)) {
            throw new \InvalidArgumentException('non-nullable dealer_code cannot be null');
        }
        $this->container['dealer_code'] = $dealer_code;

        return $this;
    }

    /**
     * Gets group_code
     *
     * @return bool|null
     */
    public function getGroupCode()
    {
        return $this->container['group_code'];
    }

    /**
     * Sets group_code
     *
     * @param bool|null $group_code group_code
     *
     * @return self
     */
    public function setGroupCode($group_code)
    {
        if (is_null($group_code)) {
            throw new \InvalidArgumentException('non-nullable group_code cannot be null');
        }
        $this->container['group_code'] = $group_code;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return bool|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param bool|null $transaction_id transaction_id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets accept_up_sell
     *
     * @return bool|null
     */
    public function getAcceptUpSell()
    {
        return $this->container['accept_up_sell'];
    }

    /**
     * Sets accept_up_sell
     *
     * @param bool|null $accept_up_sell accept_up_sell
     *
     * @return self
     */
    public function setAcceptUpSell($accept_up_sell)
    {
        if (is_null($accept_up_sell)) {
            throw new \InvalidArgumentException('non-nullable accept_up_sell cannot be null');
        }
        $this->container['accept_up_sell'] = $accept_up_sell;

        return $this;
    }

    /**
     * Gets up_sell_message
     *
     * @return bool|null
     */
    public function getUpSellMessage()
    {
        return $this->container['up_sell_message'];
    }

    /**
     * Sets up_sell_message
     *
     * @param bool|null $up_sell_message up_sell_message
     *
     * @return self
     */
    public function setUpSellMessage($up_sell_message)
    {
        if (is_null($up_sell_message)) {
            throw new \InvalidArgumentException('non-nullable up_sell_message cannot be null');
        }
        $this->container['up_sell_message'] = $up_sell_message;

        return $this;
    }

    /**
     * Gets up_sell_amount
     *
     * @return bool|null
     */
    public function getUpSellAmount()
    {
        return $this->container['up_sell_amount'];
    }

    /**
     * Sets up_sell_amount
     *
     * @param bool|null $up_sell_amount up_sell_amount
     *
     * @return self
     */
    public function setUpSellAmount($up_sell_amount)
    {
        if (is_null($up_sell_amount)) {
            throw new \InvalidArgumentException('non-nullable up_sell_amount cannot be null');
        }
        $this->container['up_sell_amount'] = $up_sell_amount;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return bool|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param bool|null $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets operator_code
     *
     * @return bool|null
     */
    public function getOperatorCode()
    {
        return $this->container['operator_code'];
    }

    /**
     * Sets operator_code
     *
     * @param bool|null $operator_code operator_code
     *
     * @return self
     */
    public function setOperatorCode($operator_code)
    {
        if (is_null($operator_code)) {
            throw new \InvalidArgumentException('non-nullable operator_code cannot be null');
        }
        $this->container['operator_code'] = $operator_code;

        return $this;
    }

    /**
     * Gets group_key
     *
     * @return bool|null
     */
    public function getGroupKey()
    {
        return $this->container['group_key'];
    }

    /**
     * Sets group_key
     *
     * @param bool|null $group_key group_key
     *
     * @return self
     */
    public function setGroupKey($group_key)
    {
        if (is_null($group_key)) {
            throw new \InvalidArgumentException('non-nullable group_key cannot be null');
        }
        $this->container['group_key'] = $group_key;

        return $this;
    }

    /**
     * Gets operator_name
     *
     * @return bool|null
     */
    public function getOperatorName()
    {
        return $this->container['operator_name'];
    }

    /**
     * Sets operator_name
     *
     * @param bool|null $operator_name operator_name
     *
     * @return self
     */
    public function setOperatorName($operator_name)
    {
        if (is_null($operator_name)) {
            throw new \InvalidArgumentException('non-nullable operator_name cannot be null');
        }
        $this->container['operator_name'] = $operator_name;

        return $this;
    }

    /**
     * Gets customer_care_number
     *
     * @return bool|null
     */
    public function getCustomerCareNumber()
    {
        return $this->container['customer_care_number'];
    }

    /**
     * Sets customer_care_number
     *
     * @param bool|null $customer_care_number customer_care_number
     *
     * @return self
     */
    public function setCustomerCareNumber($customer_care_number)
    {
        if (is_null($customer_care_number)) {
            throw new \InvalidArgumentException('non-nullable customer_care_number cannot be null');
        }
        $this->container['customer_care_number'] = $customer_care_number;

        return $this;
    }

    /**
     * Gets country_name
     *
     * @return bool|null
     */
    public function getCountryName()
    {
        return $this->container['country_name'];
    }

    /**
     * Sets country_name
     *
     * @param bool|null $country_name country_name
     *
     * @return self
     */
    public function setCountryName($country_name)
    {
        if (is_null($country_name)) {
            throw new \InvalidArgumentException('non-nullable country_name cannot be null');
        }
        $this->container['country_name'] = $country_name;

        return $this;
    }

    /**
     * Gets cpf
     *
     * @return bool|null
     */
    public function getCpf()
    {
        return $this->container['cpf'];
    }

    /**
     * Sets cpf
     *
     * @param bool|null $cpf cpf
     *
     * @return self
     */
    public function setCpf($cpf)
    {
        if (is_null($cpf)) {
            throw new \InvalidArgumentException('non-nullable cpf cannot be null');
        }
        $this->container['cpf'] = $cpf;

        return $this;
    }

    /**
     * Gets send_value
     *
     * @return bool|null
     */
    public function getSendValue()
    {
        return $this->container['send_value'];
    }

    /**
     * Sets send_value
     *
     * @param bool|null $send_value send_value
     *
     * @return self
     */
    public function setSendValue($send_value)
    {
        if (is_null($send_value)) {
            throw new \InvalidArgumentException('non-nullable send_value cannot be null');
        }
        $this->container['send_value'] = $send_value;

        return $this;
    }

    /**
     * Gets receive_value
     *
     * @return bool|null
     */
    public function getReceiveValue()
    {
        return $this->container['receive_value'];
    }

    /**
     * Sets receive_value
     *
     * @param bool|null $receive_value receive_value
     *
     * @return self
     */
    public function setReceiveValue($receive_value)
    {
        if (is_null($receive_value)) {
            throw new \InvalidArgumentException('non-nullable receive_value cannot be null');
        }
        $this->container['receive_value'] = $receive_value;

        return $this;
    }

    /**
     * Gets receive_currency_iso
     *
     * @return bool|null
     */
    public function getReceiveCurrencyIso()
    {
        return $this->container['receive_currency_iso'];
    }

    /**
     * Sets receive_currency_iso
     *
     * @param bool|null $receive_currency_iso receive_currency_iso
     *
     * @return self
     */
    public function setReceiveCurrencyIso($receive_currency_iso)
    {
        if (is_null($receive_currency_iso)) {
            throw new \InvalidArgumentException('non-nullable receive_currency_iso cannot be null');
        }
        $this->container['receive_currency_iso'] = $receive_currency_iso;

        return $this;
    }

    /**
     * Gets send_currency_iso
     *
     * @return bool|null
     */
    public function getSendCurrencyIso()
    {
        return $this->container['send_currency_iso'];
    }

    /**
     * Sets send_currency_iso
     *
     * @param bool|null $send_currency_iso send_currency_iso
     *
     * @return self
     */
    public function setSendCurrencyIso($send_currency_iso)
    {
        if (is_null($send_currency_iso)) {
            throw new \InvalidArgumentException('non-nullable send_currency_iso cannot be null');
        }
        $this->container['send_currency_iso'] = $send_currency_iso;

        return $this;
    }

    /**
     * Gets receive_value_excluding_tax
     *
     * @return bool|null
     */
    public function getReceiveValueExcludingTax()
    {
        return $this->container['receive_value_excluding_tax'];
    }

    /**
     * Sets receive_value_excluding_tax
     *
     * @param bool|null $receive_value_excluding_tax receive_value_excluding_tax
     *
     * @return self
     */
    public function setReceiveValueExcludingTax($receive_value_excluding_tax)
    {
        if (is_null($receive_value_excluding_tax)) {
            throw new \InvalidArgumentException('non-nullable receive_value_excluding_tax cannot be null');
        }
        $this->container['receive_value_excluding_tax'] = $receive_value_excluding_tax;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return bool|null
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param bool|null $tax_rate tax_rate
     *
     * @return self
     */
    public function setTaxRate($tax_rate)
    {
        if (is_null($tax_rate)) {
            throw new \InvalidArgumentException('non-nullable tax_rate cannot be null');
        }
        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets tax_name
     *
     * @return bool|null
     */
    public function getTaxName()
    {
        return $this->container['tax_name'];
    }

    /**
     * Sets tax_name
     *
     * @param bool|null $tax_name tax_name
     *
     * @return self
     */
    public function setTaxName($tax_name)
    {
        if (is_null($tax_name)) {
            throw new \InvalidArgumentException('non-nullable tax_name cannot be null');
        }
        $this->container['tax_name'] = $tax_name;

        return $this;
    }

    /**
     * Gets tax_calculation
     *
     * @return bool|null
     */
    public function getTaxCalculation()
    {
        return $this->container['tax_calculation'];
    }

    /**
     * Sets tax_calculation
     *
     * @param bool|null $tax_calculation tax_calculation
     *
     * @return self
     */
    public function setTaxCalculation($tax_calculation)
    {
        if (is_null($tax_calculation)) {
            throw new \InvalidArgumentException('non-nullable tax_calculation cannot be null');
        }
        $this->container['tax_calculation'] = $tax_calculation;

        return $this;
    }

    /**
     * Gets customer_fee
     *
     * @return bool|null
     */
    public function getCustomerFee()
    {
        return $this->container['customer_fee'];
    }

    /**
     * Sets customer_fee
     *
     * @param bool|null $customer_fee customer_fee
     *
     * @return self
     */
    public function setCustomerFee($customer_fee)
    {
        if (is_null($customer_fee)) {
            throw new \InvalidArgumentException('non-nullable customer_fee cannot be null');
        }
        $this->container['customer_fee'] = $customer_fee;

        return $this;
    }

    /**
     * Gets distributor_fee
     *
     * @return bool|null
     */
    public function getDistributorFee()
    {
        return $this->container['distributor_fee'];
    }

    /**
     * Sets distributor_fee
     *
     * @param bool|null $distributor_fee distributor_fee
     *
     * @return self
     */
    public function setDistributorFee($distributor_fee)
    {
        if (is_null($distributor_fee)) {
            throw new \InvalidArgumentException('non-nullable distributor_fee cannot be null');
        }
        $this->container['distributor_fee'] = $distributor_fee;

        return $this;
    }

    /**
     * Gets commission_rate
     *
     * @return bool|null
     */
    public function getCommissionRate()
    {
        return $this->container['commission_rate'];
    }

    /**
     * Sets commission_rate
     *
     * @param bool|null $commission_rate commission_rate
     *
     * @return self
     */
    public function setCommissionRate($commission_rate)
    {
        if (is_null($commission_rate)) {
            throw new \InvalidArgumentException('non-nullable commission_rate cannot be null');
        }
        $this->container['commission_rate'] = $commission_rate;

        return $this;
    }

    /**
     * Gets processing_mode
     *
     * @return bool|null
     */
    public function getProcessingMode()
    {
        return $this->container['processing_mode'];
    }

    /**
     * Sets processing_mode
     *
     * @param bool|null $processing_mode processing_mode
     *
     * @return self
     */
    public function setProcessingMode($processing_mode)
    {
        if (is_null($processing_mode)) {
            throw new \InvalidArgumentException('non-nullable processing_mode cannot be null');
        }
        $this->container['processing_mode'] = $processing_mode;

        return $this;
    }

    /**
     * Gets redemption_mechanism
     *
     * @return bool|null
     */
    public function getRedemptionMechanism()
    {
        return $this->container['redemption_mechanism'];
    }

    /**
     * Sets redemption_mechanism
     *
     * @param bool|null $redemption_mechanism redemption_mechanism
     *
     * @return self
     */
    public function setRedemptionMechanism($redemption_mechanism)
    {
        if (is_null($redemption_mechanism)) {
            throw new \InvalidArgumentException('non-nullable redemption_mechanism cannot be null');
        }
        $this->container['redemption_mechanism'] = $redemption_mechanism;

        return $this;
    }

    /**
     * Gets sku_code
     *
     * @return bool|null
     */
    public function getSkuCode()
    {
        return $this->container['sku_code'];
    }

    /**
     * Sets sku_code
     *
     * @param bool|null $sku_code sku_code
     *
     * @return self
     */
    public function setSkuCode($sku_code)
    {
        if (is_null($sku_code)) {
            throw new \InvalidArgumentException('non-nullable sku_code cannot be null');
        }
        $this->container['sku_code'] = $sku_code;

        return $this;
    }

    /**
     * Gets localization_key
     *
     * @return bool|null
     */
    public function getLocalizationKey()
    {
        return $this->container['localization_key'];
    }

    /**
     * Sets localization_key
     *
     * @param bool|null $localization_key localization_key
     *
     * @return self
     */
    public function setLocalizationKey($localization_key)
    {
        if (is_null($localization_key)) {
            throw new \InvalidArgumentException('non-nullable localization_key cannot be null');
        }
        $this->container['localization_key'] = $localization_key;

        return $this;
    }

    /**
     * Gets additional_information
     *
     * @return bool|null
     */
    public function getAdditionalInformation()
    {
        return $this->container['additional_information'];
    }

    /**
     * Sets additional_information
     *
     * @param bool|null $additional_information additional_information
     *
     * @return self
     */
    public function setAdditionalInformation($additional_information)
    {
        if (is_null($additional_information)) {
            throw new \InvalidArgumentException('non-nullable additional_information cannot be null');
        }
        $this->container['additional_information'] = $additional_information;

        return $this;
    }

    /**
     * Gets default_display_text
     *
     * @return bool|null
     */
    public function getDefaultDisplayText()
    {
        return $this->container['default_display_text'];
    }

    /**
     * Sets default_display_text
     *
     * @param bool|null $default_display_text default_display_text
     *
     * @return self
     */
    public function setDefaultDisplayText($default_display_text)
    {
        if (is_null($default_display_text)) {
            throw new \InvalidArgumentException('non-nullable default_display_text cannot be null');
        }
        $this->container['default_display_text'] = $default_display_text;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return bool|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param bool|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets charge_value
     *
     * @return bool|null
     */
    public function getChargeValue()
    {
        return $this->container['charge_value'];
    }

    /**
     * Sets charge_value
     *
     * @param bool|null $charge_value charge_value
     *
     * @return self
     */
    public function setChargeValue($charge_value)
    {
        if (is_null($charge_value)) {
            throw new \InvalidArgumentException('non-nullable charge_value cannot be null');
        }
        $this->container['charge_value'] = $charge_value;

        return $this;
    }

    /**
     * Gets charge_currency_iso
     *
     * @return bool|null
     */
    public function getChargeCurrencyIso()
    {
        return $this->container['charge_currency_iso'];
    }

    /**
     * Sets charge_currency_iso
     *
     * @param bool|null $charge_currency_iso charge_currency_iso
     *
     * @return self
     */
    public function setChargeCurrencyIso($charge_currency_iso)
    {
        if (is_null($charge_currency_iso)) {
            throw new \InvalidArgumentException('non-nullable charge_currency_iso cannot be null');
        }
        $this->container['charge_currency_iso'] = $charge_currency_iso;

        return $this;
    }

    /**
     * Gets client_ip
     *
     * @return bool|null
     */
    public function getClientIp()
    {
        return $this->container['client_ip'];
    }

    /**
     * Sets client_ip
     *
     * @param bool|null $client_ip client_ip
     *
     * @return self
     */
    public function setClientIp($client_ip)
    {
        if (is_null($client_ip)) {
            throw new \InvalidArgumentException('non-nullable client_ip cannot be null');
        }
        $this->container['client_ip'] = $client_ip;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return bool|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param bool|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets zone_id
     *
     * @return bool|null
     */
    public function getZoneId()
    {
        return $this->container['zone_id'];
    }

    /**
     * Sets zone_id
     *
     * @param bool|null $zone_id zone_id
     *
     * @return self
     */
    public function setZoneId($zone_id)
    {
        if (is_null($zone_id)) {
            throw new \InvalidArgumentException('non-nullable zone_id cannot be null');
        }
        $this->container['zone_id'] = $zone_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


