<?php
/**
 * PartnersAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pagaqui.Services.Partners.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PartnersAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PartnersAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for partnersAPIAuthenticate
     *
     * .
     *
     */
    public function testPartnersAPIAuthenticate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPICancelTransaction
     *
     * .
     *
     */
    public function testPartnersAPICancelTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIDoCalculateEstimatePrice
     *
     * .
     *
     */
    public function testPartnersAPIDoCalculateEstimatePrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIDoTransaction
     *
     * .
     *
     */
    public function testPartnersAPIDoTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetAvailableProduct
     *
     * .
     *
     */
    public function testPartnersAPIGetAvailableProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetAvailableProductByCode
     *
     * .
     *
     */
    public function testPartnersAPIGetAvailableProductByCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetAvailableProductOptionByCode
     *
     * .
     *
     */
    public function testPartnersAPIGetAvailableProductOptionByCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetAvailableProductTypes
     *
     * .
     *
     */
    public function testPartnersAPIGetAvailableProductTypes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetCountries
     *
     * .
     *
     */
    public function testPartnersAPIGetCountries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetInternationalMobileProducts
     *
     * .
     *
     */
    public function testPartnersAPIGetInternationalMobileProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetInternationalOperators
     *
     * .
     *
     */
    public function testPartnersAPIGetInternationalOperators()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetInternationalPhoneNumberOptions
     *
     * .
     *
     */
    public function testPartnersAPIGetInternationalPhoneNumberOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetProductOptionPhoneNumber
     *
     * .
     *
     */
    public function testPartnersAPIGetProductOptionPhoneNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnersAPIGetTransaction
     *
     * .
     *
     */
    public function testPartnersAPIGetTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
